package-lock.json
package.json

This also fixes a memory leak in (NPM-package) "mem".

:arrow_up: Updated NPM packages

---

src/openzaak/components/authorizations/openapi.yaml
src/openzaak/components/authorizations/swagger2.0.json

Issue - https://github.com/open-zaak/open-zaak/issues/105

regenerate schema to update discriminator values

---

src/openzaak/components/catalogi/admin/zaaktypen.py

Issue - https://github.com/open-zaak/open-zaak/issues/101
Changes:
1. remove ZaakTypeObjectAdmin from ZaakTypeAdmin

Fix ZaakTypeAdmin 500 error

---

src/openzaak/components/documenten/api/serializers.py
src/openzaak/components/documenten/api/validators.py
src/openzaak/components/documenten/api/viewsets.py
src/openzaak/components/documenten/tests/test_audittrails.py
src/openzaak/components/documenten/tests/test_objectinformatieobject.py

Issue - https://github.com/open-zaak/open-zaak/issues/158

Issue/forbid non-unique oio create

---

src/openzaak/components/besluiten/tests/test_besluit_create.py
src/openzaak/loaders.py

issue - https://github.com/open-zaak/open-zaak/issues/119

fix external fk for non-JSON urls

---

src/openzaak/components/catalogi/admin/eigenschap.py
src/openzaak/components/catalogi/admin/informatieobjecttype.py
src/openzaak/components/catalogi/admin/roltype.py
src/openzaak/components/catalogi/admin/statustype.py
src/openzaak/components/catalogi/admin/zaaktypen.py

Things I ran into for Utrecht...

Fix admin after field removal

---

src/openzaak/components/catalogi/api/filters.py
src/openzaak/components/catalogi/api/viewsets/mixins.py
src/openzaak/components/catalogi/api/viewsets/relatieklassen.py
src/openzaak/components/catalogi/tests/test_relatieklassen.py

same fixes as: https://github.com/VNG-Realisatie/gemma-zaaktypecatalogus/commit/a4d9ecfa4a464a1562189285ededd63831833ed3

Fix concept-derivation of ZIOT

---

src/openzaak/components/catalogi/api/serializers/relatieklassen.py
src/openzaak/components/catalogi/tests/test_relatieklassen.py

Issue - https://github.com/open-zaak/open-zaak/issues/165

add UniqueTogetherValidator to ZIOT serializer

---

src/openzaak/components/catalogi/api/serializers/informatieobjecttype.py
src/openzaak/components/catalogi/tests/test_informatieobjecttype.py

Issue - https://github.com/open-zaak/open-zaak/issues/159

add UniqueTogetherValidator to InformatieObjectType

---

src/openzaak/components/besluiten/api/serializers.py
src/openzaak/components/besluiten/api/validators.py
src/openzaak/components/besluiten/tests/test_validation.py

Issue - https://github.com/open-zaak/open-zaak/issues/156

change code and rename BesluittypeInformatieobjecttypeRelationValidator

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/zaken/tests/test_zaakinformatieobjecten.py
src/openzaak/loaders.py
src/openzaak/utils/validators.py

Updated django-loose-fk to get a single validation error

Fix crash on invalid URLs for ZIO

---

src/openzaak/components/catalogi/api/scopes.py

to be consistent with https://github.com/VNG-Realisatie/gemma-zaaktypecatalogus/pull/83#discussion_r344861274

Change forced_delete for catalogi scope name from geforceerd_verwijderen to geforceerd-verwijderen

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Issue - https://github.com/open-zaak/open-zaak/issues/193

Update django-better-admin-arrayfield version

---

src/openzaak/utils/templates/admin/edit_inline/tabular_add_and_edit.html

Issue - https://github.com/open-zaak/open-zaak/issues/160

change condition to represent inline objects in templates

---

src/openzaak/components/zaken/admin/zaken.py

Changes:
1. add `zaaktype` and `hoofdzaak` to raw_id_fields for `ZaakAdmin`

raw_id_fields in ZaakAdmin

---

src/openzaak/components/catalogi/models/zaaktype.py

Issue - https://github.com/open-zaak/open-zaak/issues/192

fix zaaktype.datum_begin_geldigheid in the admin

---

src/openzaak/components/catalogi/api/kanalen.py
src/openzaak/components/catalogi/api/viewsets/besluittype.py
src/openzaak/components/catalogi/api/viewsets/informatieobjecttype.py
src/openzaak/components/catalogi/api/viewsets/zaaktype.py

fixes https://github.com/open-zaak/open-zaak/issues/229
since I also got an error when I tried to register_kanaal without the proper config, I made a fix for that in open-notificaties https://github.com/open-zaak/open-notificaties/pull/3

Fixes #229 -- Added notificatie kanalen for Catalogi

---

src/openzaak/components/besluiten/admin.py
src/openzaak/components/besluiten/tests/admin/test_besluit_audittrail.py
src/openzaak/components/besluiten/tests/admin/test_besluitinformatieobject_audittrail.py
src/openzaak/components/documenten/admin.py
src/openzaak/components/documenten/tests/admin/test_eio_audittrail.py
src/openzaak/components/documenten/tests/admin/test_gebruiksrechten_audittrail.py
src/openzaak/components/zaken/admin/zaken.py
src/openzaak/components/zaken/tests/admin/test_klantcontact_audittrail.py
src/openzaak/components/zaken/tests/admin/test_resultaat_audittrail.py
src/openzaak/components/zaken/tests/admin/test_rol_audittrail.py
src/openzaak/components/zaken/tests/admin/test_status_audittrail.py
src/openzaak/components/zaken/tests/admin/test_zaak_audittrail.py
src/openzaak/components/zaken/tests/admin/test_zaakeigenschap_audittrail.py
src/openzaak/components/zaken/tests/admin/test_zaakinformatieobject_audittrail.py
src/openzaak/components/zaken/tests/admin/test_zaakobject_audittrail.py
src/openzaak/utils/admin.py
src/openzaak/utils/tests.py

issue - https://github.com/open-zaak/open-zaak/issues/169

log Admin changes to AuditTrail

---

deployment/provision.yml
deployment/vars/db_credentials.example.yml
docs/installation/deployment/kubernetes.rst
docs/installation/index.rst

Fixes #9 as well.
I'm sure there is a lot to improve on :-)

Fixes #148  -- Document deploying on Kubernetes

---

deployment/files/traefik/deployment.yml

Fix ACME challenge by reverting to http instead of tls

---

src/openzaak/components/zaken/api/serializers/zaakobjecten.py

fixes https://github.com/open-zaak/open-zaak/issues/269

Fixes #269 -- Added auth to URLValidator for ZaakObject.object

---

src/openzaak/components/catalogi/api/validators.py
src/openzaak/components/catalogi/models/zaaktype.py
src/openzaak/components/catalogi/tests/models/test_zaaktype_validation.py
src/openzaak/components/catalogi/utils.py

...and make sure the end validity is exclusive.
Do you recognize your own code? ;-)

Refactor overlap-detection into shared function

---

src/openzaak/components/catalogi/models/zaaktype.py
src/openzaak/components/catalogi/tests/admin/test_zaaktype_admin.py
src/openzaak/components/catalogi/tests/test_relativedelta_comparison.py
src/openzaak/components/catalogi/utils.py

... dealing with time is stupid.

Set up a way to compare relative deltas - fixes catalogus export bug

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Upstream is not exactly responsive to pull requests, so we had to fork.
This silences the stdout output during tests runs because of print
statements.

Replace django-better-admin-arrayfield with own fork

---

requirements/dev.txt

Bump Waitress in dev settings as well

---

src/openzaak/templates/admin/object_history.html

fixes https://github.com/open-zaak/open-zaak/issues/381

Fixes #381 -- fixed audittrail styling and javascript in admin

---

docs/manual/index.rst
docs/manual/logging.rst

issue https://github.com/open-zaak/open-zaak/issues/11

Fixes #11 -- added documentation for logging

---

src/openzaak/components/besluiten/admin.py
src/openzaak/components/catalogi/admin/besluittype.py
src/openzaak/components/catalogi/admin/catalogus.py
src/openzaak/components/catalogi/admin/eigenschap.py
src/openzaak/components/catalogi/admin/informatieobjecttype.py
src/openzaak/components/catalogi/admin/resultaattype.py
src/openzaak/components/catalogi/admin/roltype.py
src/openzaak/components/catalogi/admin/statustype.py
src/openzaak/components/catalogi/admin/zaaktypen.py
src/openzaak/components/documenten/admin.py
src/openzaak/components/zaken/admin/zaken.py

and added missing uuidfields in detail pages
issue https://github.com/open-zaak/open-zaak/issues/401

Fixes #401 -- made UUID fields readonly in admin

---

CONTRIBUTE.md

issue https://github.com/open-zaak/open-zaak/issues/20

Fixes #20 -- added contribution guidelines for Open Zaak

---

src/openzaak/components/autorisaties/api/serializers.py
src/openzaak/components/autorisaties/api/viewsets.py
src/openzaak/components/autorisaties/forms.py
src/openzaak/components/autorisaties/tests/admin/test_applications_admin.py
src/openzaak/components/autorisaties/tests/test_authorizations_api.py

issue - https://github.com/open-zaak/open-zaak/issues/301

Autorisatie admin with external credentials

---

docs/installation/deployment/single_server.rst

Takes feedback from gemeente Buren and includes the example from here: https://github.com/open-zaak/open-zaak/pull/382/files#diff-c72bb89a0b3ab64f1449eb83a2f5f46a

Install to self hints

---

src/openzaak/sass/admin/_admin_theme.scss

Fixes #184 -- changed default admin detail help_text to tooltip mouseover

---

src/openzaak/templates/index.html
src/openzaak/templates/main.html
src/openzaak/urls.py
src/openzaak/utils/views.py

related to https://github.com/open-zaak/open-zaak/pull/440
this only leaves the checks for site domain, https, nrc configuration, nrc credentials and nrc authorizations

Minor changes to view-config page

---

src/openzaak/management/commands/send_test_notification.py

Added management command to test notification sending

---

src/openzaak/components/autorisaties/forms.py
src/openzaak/components/autorisaties/tests/admin/test_autorisaties_admin.py

issue - https://github.com/open-zaak/open-zaak/issues/356

check for zaaktype overlap in the auth admin

---

src/openzaak/components/besluiten/tests/test_auth.py
src/openzaak/components/documenten/tests/test_auth.py
src/openzaak/components/zaken/tests/test_auth.py

fixes https://github.com/open-zaak/open-zaak/issues/314

test permission check with external resources

---

src/openzaak/components/catalogi/admin/admin_views.py
src/openzaak/components/catalogi/admin/mixins.py
src/openzaak/components/catalogi/tests/admin/test_admin_publish.py
src/openzaak/components/catalogi/tests/admin/test_import_export_catalogus.py
src/openzaak/components/catalogi/tests/admin/test_import_export_zaaktype.py
src/openzaak/templates/admin/catalogi/change_form.html
src/openzaak/templates/admin/catalogi/change_form_catalogus.html
src/openzaak/templates/admin/catalogi/change_list_catalogus.html

Fixes #443 -- block publish/import/export buttons for read-only users

---

src/openzaak/components/autorisaties/tests/test_jwt.py
src/openzaak/utils/permissions.py

issue - https://github.com/open-zaak/open-zaak/issues/463#event-3006034800

fix PermissionDenied when iat is misssing in jwt

---

src/openzaak/components/zaken/tests/test_zaak_closed.py

Issue - https://github.com/open-zaak/open-zaak/pull/451#issuecomment-581904630

set omschrijving_generiek to prevent triggering RolOccurenceValidator

---

.bumpversion.cfg
CHANGELOG.rst
Dockerfile
README.rst
bin/docker_push.sh
deployment/kubernetes/apps.yml
deployment/single-server/open-zaak.yml
package-lock.json
package.json

Draft 1.0.0 release

---

.travis.yml
src/openzaak/components/besluiten/admin.py
src/openzaak/components/besluiten/tests/admin/test_besluit_audittrail.py
src/openzaak/components/besluiten/tests/admin/test_besluit_model_form.py
src/openzaak/components/besluiten/tests/admin/test_besluitinformatieobject_model_form.py
src/openzaak/components/documenten/admin.py
src/openzaak/components/documenten/tests/admin/test_objectinformationobject_model_form.py
src/openzaak/components/zaken/admin/zaken.py
src/openzaak/components/zaken/tests/admin/test_relevantezaakrelatie_model_form.py
src/openzaak/components/zaken/tests/admin/test_resultaat_model_form.py
src/openzaak/components/zaken/tests/admin/test_rol_model_form.py
src/openzaak/components/zaken/tests/admin/test_statusform_model_form.py
src/openzaak/components/zaken/tests/admin/test_zaak_model_form.py
src/openzaak/components/zaken/tests/admin/test_zaakbesluit_model_form.py
src/openzaak/components/zaken/tests/admin/test_zaakeigenschap_model_form.py
src/openzaak/components/zaken/tests/admin/test_zaakinformatieobject_model_form.py

Fix for issue https://github.com/open-zaak/open-zaak/issues/467
Now instead of a 500 you'll see something similar to the below screenshot

Add ModelForms to validate input data required on a model/database level

---

docs/manual/index.rst
docs/manual/other_apis.rst
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/bag/tests/__init__.py
src/openzaak/components/zaken/tests/test_zaakobject.py
src/openzaak/conf/includes/api.py
src/openzaak/conf/includes/base.py
src/openzaak/fixtures/default_admin_index.json
src/openzaak/nlx/__init__.py

Support NLX to fetch objects in other APIs

---

.bumpversion.cfg
CHANGELOG.rst
README.rst
deployment/kubernetes/apps.yml
deployment/single-server/open-zaak.yml
docs/manual/index.rst
docs/manual/other_apis.rst
package-lock.json
package.json
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/bag/tests/__init__.py
src/openzaak/components/zaken/tests/test_zaakobject.py
src/openzaak/conf/includes/api.py
src/openzaak/conf/includes/base.py
src/openzaak/fixtures/default_admin_index.json
src/openzaak/nlx/__init__.py

Release 1.0.4

---

.bumpversion.cfg
CHANGELOG.rst
README.rst
deployment/kubernetes/apps.yml
deployment/kubernetes/requirements.yml
deployment/single-server/open-zaak.yml
deployment/single-server/requirements.yml
deployment/single-server/vars/nlx.example.yml
package.json

Release 1.1.0

---

deployment/kubernetes/requirements.yml
deployment/single-server/requirements.yml

Discovered while testing an installation and attempting to download the document from the admin interface.

Fix nginx permissions to serve files from documents API

---

bin/generate_admin_index_fixture.sh
src/openzaak/fixtures/default_admin_index.json

- Added script to generate a new version of the admin-index fixture.
- Added an updated version of the admin-index, using correct ordering and moved access logs from the config to the logs group.

Admin index update

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/documenten/admin.py
src/openzaak/components/documenten/api/viewsets.py
src/openzaak/components/documenten/tests/admin/test_eio_download.py
src/openzaak/components/documenten/tests/test_eio_file.py
src/openzaak/components/documenten/tests/test_enkelvoudiginformatieobject.py
src/openzaak/components/documenten/views.py
src/openzaak/components/documenten/widgets.py
src/openzaak/conf/dev.py
src/openzaak/conf/includes/base.py

issue: https://github.com/open-zaak/open-zaak/issues/507

Fixes #507 -- added download with original filename to EIO admin

---

.bumpversion.cfg
CHANGELOG.rst
README.rst
deployment/kubernetes/apps.yml
deployment/single-server/open-zaak.yml
package-lock.json
package.json

Prepare release 1.2.0

---

src/openzaak/tests/api_strategy/test_disabled.py

**Changes**
* tests stop failing when testing with --keepdb

fix disabled tests with keepdb option

---

src/openzaak/components/catalogi/admin/forms.py
src/openzaak/components/catalogi/tests/admin/test_informatieobjecttype_admin.py

Fixes # https://sentry.maykinmedia.nl/maykin-media/open-zaak-utrecht-test/issues/269711/?query=is%3Aunresolved

fix ziot admin form

---

src/openzaak/components/catalogi/constants.py
src/openzaak/components/catalogi/tests/admin/test_import_export_catalogus.py

Fixes https://github.com/open-zaak/open-zaak/issues/568

fix importing ziot with statustype

---

deployment/kubernetes/apps.yml
deployment/kubernetes/vars/nlx.example.yml
deployment/kubernetes/vars/open-notificaties.example.yml
deployment/kubernetes/vars/open-zaak.example.yml
docs/installation/deployment/kubernetes.rst

Improved k8s configuration with examples and references to roles.

:pencil: Added various hints for k8s deployments

---

src/openzaak/config/forms.py
src/openzaak/js/components/admin/external-services/nlx.js

Fixes https://sentry.maykinmedia.nl/maykin-media/open-zaak-public-test/issues/270076/tags/url/

fix exteral services form when nlx directory is not set up

---

docs/conf.md
docs/development/performance/index.rst
docs/development/performance/profiling.rst
requirements/dev.in
requirements/dev.txt
src/openzaak/components/zaken/api/viewsets.py
src/openzaak/conf/dev.py
src/openzaak/urls.py

Fixes #599
**Changes**
* added django-silk to profile queries/requests in DRF (django debug toolbar does not support this)
* added whitenoise to support the django-silk interface with `DEBUG=no` (in DEBUG mode, Django keeps a log of queries and is slower in general)
* added a prefetch related to the zaak viewset
* added a select related in the zaak viewset
---
All testing was done on my local machine. A database dump from Gemeente Utrecht was loaded in my machine to compare the results (same dataset from #599). Absolute numbers between dev/proeftuin environment cannot be compared because of the big hardware differences. However, benchmarks were run to establish a baseline.
**Baseline - no changes**
The `/zaken/api/v1/zaken` endpoint was hit 10 times in total, with no changes in data.
| …

Optimize zaak-list endpoint

---

src/openzaak/components/zaken/tests/test_statussen.py
src/openzaak/utils/permissions.py

Fixes #604 
**Changes**
Attempts to resolve database objects that raise validation errors (such as UUIDField) now reach the client as a validation error, instead of triggering a server error.

Fix server error that should be a validation error

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/conf/includes/base.py

Builds on #626 
**Changes**
Grab CMIS settings from the environment.

Set CMIS settings based on env.

---

docs/development/getting_started.rst

Addresses #633
**Changes**
Added note for Git on Windows and docker-compose command.

Added Git on Windows note to docs

---

docs/support/index.rst

Added Slack invite link.

---

deployment/appliance/README.rst
docs/installation/hardware.rst
docs/introduction/index.rst
publiccode.yaml

Don't forget that there's a rat in separate!

Fix spelling of "separate"

---

CONTRIBUTING.md

Clarifying on issues and give more tips about the Standard 
and link to the mailing list.

Improving contributing file

---

docs/installation/cli.rst
docs/installation/index.rst
src/openzaak/accounts/management/commands/createinitialsuperuser.py
src/openzaak/accounts/tests/test_createinitialsuperuser.py

**Changes**
* adds the `createinitialsuperuser` command

Added createinitialsuperuser command + tests

---

docs/installation/deployment/single_server.rst

Fixes #663
**Changes**
Added hint for space on `/var/lib/docker`.

Added hint for Docker folder storage.

---

src/openzaak/components/documenten/api/serializers.py
src/openzaak/components/documenten/models.py
src/openzaak/conf/includes/base.py

Fixes the generation of API schemas which were empty

Reverted API default setting

---

.bumpversion.cfg
CHANGELOG.rst
README.en.md
README.rst
deployment/kubernetes/apps.yml
deployment/single-server/open-zaak.yml
package-lock.json
package.json
src/openzaak/components/documenten/openapi.yaml
src/openzaak/components/documenten/swagger2.0.json
src/openzaak/components/zaken/openapi.yaml
src/openzaak/components/zaken/swagger2.0.json

**Changes**
* Updated CMIS-adapter to 1.1 featuring support CMIS 1.0 Webservice binding and
various new configuration options.
* Added support for configurable Selectielijst years to retrieve specific years
from the Selectielijst API (#689)
* Prevent error monitoring from logging special personal data (#696)
**Bugfixes**
* Accept comma separated in ``EigenschapSpecificatie.waardenverzameling`` (#686)
**Documentation**
* Added SPDX license headers and check.
* Added Docker storage hint to make sure users run the Docker containers on
volumes with enough disk space.

Release 1.3.1

---

GOVERNANCE.md

During the first community call, these memberships were approved.
Related to #620
**Changes**
* Added Joeri & Sergei (myself) to the technical steering team members
* Added Joeri to the product steering team members

Add Joeri & Sergei to steering teams

---

docs/installation/config/openzaak_config.rst

[#722] Documentation correction

---

GOVERNANCE.md

**Changes**
As per previous meeting, the members and desired roles to take place in the product steering team have been refined as proposal.

Update members and specify typical roles

---

GOVERNANCE.md
docs/development/index.rst
docs/development/principles.rst
docs/development/roadmap.rst

Fixes #675 
Governance:
- added Tahir & Tjerk to the members
- reworded responsibilities
- moved CoC violation handling to the CoC section
Roadmap:
- added impact for items
- added t-shirt sizing for items
Principles, architecture, code style
- added backend code style/guidelines
- added frontend code style/guidelines

Prepare next technical steering group meeting

---

package-lock.json
package.json

Fix npm packages with known security issues

---

docs/introduction/open-source/public_code.md

Fixed broken link in the documentation

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/documenten/tests/test_enkelvoudiginformatieobject_cmis.py

Fixes #760 
**Changes**
The CMIS adapter was updated to include the bug fixes for binary files.
A test was also added.

Issue 760 bug with binary documents

---

deployment/requirements.txt
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Follow up on dependabot PRs.
**Changes**
* bumped the version of cryptography in deployment and production dependencies

Bump cryptography

---

.bumpversion.cfg
CHANGELOG.rst
README.en.md
README.rst
deployment/kubernetes/apps.yml
deployment/single-server/open-zaak.yml
package-lock.json
package.json

Version bump and changelog for bugfix release 1.3.2

Release 1.3.2

---

GOVERNANCE.md

Fix typo "join" -> "joint"

---

docs/installation/config/cmis.rst
docs/installation/config/env_config.md
docs/installation/config/openzaak_config.rst
docs/support/index.rst

Fixed a couple of documentation typos.

Typos in documentation

---

docs/installation/config/cmis.rst
docs/installation/config/env_config.md

Documentation on how to disable SSL/TLS certificate verification

---

src/openzaak/components/documenten/tests/test_audittrails.py
src/openzaak/components/documenten/tests/test_audittrails_cmis.py

Fixes #798
**Changes**
Attempt to make tests (more) deterministic

Fixes #798 -- Check if it's ordering related?

---

deployment/single-server/nlx.yml
deployment/single-server/open-zaak.yml
deployment/single-server/requirements.yml
docs/installation/deployment/single_server.rst

Prepared the update ~~pending PR https://github.com/open-zaak/ansible-collection/pull/9~~
This makes the playbook more OS "agnostic" and the documentation mentions supported OS flavours.

Deployment playbook single-server update

---

src/openzaak/components/catalogi/tests/admin/test_import_export_zaaktype.py

Fixes #813 
Tries ordering  queryset in test to see if that fixes the occasional error.

Fixes #813 - Heisenbug in tests

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
requirements/test-tools.in
src/openzaak/components/autorisaties/tests/test_notifications_send.py
src/openzaak/components/besluiten/api/viewsets.py
src/openzaak/components/besluiten/tests/test_besluitinformatieobjecten.py
src/openzaak/components/besluiten/tests/test_notifications_send.py
src/openzaak/components/besluiten/tests/test_notifications_send_cmis.py
src/openzaak/components/catalogi/tests/admin/test_admin_publish.py
src/openzaak/components/catalogi/tests/admin/test_import_export_zaaktype.py
src/openzaak/components/catalogi/tests/admin/test_zaaktype_admin.py
src/openzaak/components/catalogi/tests/test_notifications_send.py
src/openzaak/components/documenten/tests/test_notifications_send.py
src/openzaak/components/documenten/tests/test_notifications_send_cmis.py
src/openzaak/components/zaken/api/serializers/zaken.py
src/openzaak/components/zaken/api/viewsets.py
src/openzaak/components/zaken/tests/test_notifications_send.py
src/openzaak/components/zaken/tests/test_notifications_send_cmis.py
src/openzaak/components/zaken/tests/test_zaakinformatieobjecten.py
src/openzaak/utils/tests.py

Fix remote DRC documenten integration issues

---

docs/support/index.rst

Related issue at #832 
Added Contezza as service provider

Added Contezza as service provider

---

SECURITY.rst
docs/support/index.rst
docs/support/security.rst

Fixes #831
**Changes**
* Added security process documentation to the root of the repo
* Included security documentation in main docs build

Fixes #831 -- document security issue process

---

src/openzaak/conf/production.py

Fixes #741
**Changes**
* Only prefix `subpath` if it's longer than `/`

Build correct STATIC_URL and MEDIA_URL

---

docs/installation/config/openzaak_config.rst

Fixes #666
**Changes**
* Add process of registering kanalen to config docs

:memo: Add registering of kanalen to config docs

---

src/openzaak/components/catalogi/admin/mixins.py
src/openzaak/components/catalogi/models/mixins.py
src/openzaak/components/catalogi/tests/admin/test_besluittype_admin.py
src/openzaak/components/catalogi/tests/admin/test_informatieobjecttype_admin.py
src/openzaak/components/catalogi/tests/admin/test_zaaktype_admin.py
src/openzaak/components/catalogi/tests/factories/besluittype.py
src/openzaak/components/catalogi/tests/test_besluittype.py

Fixes #838
**Changes**
* admin action `publish_selected` is created

publish selected objects in the admin

---

SECURITY.rst

**Changes**
Adds helpful link to the mailing list.

Add link to mailing list

---

deployment/requirements.txt
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Fixes #856
Fixes #858
Fixes #859
**Changes**
Bumped `cryptography` and `httplib` following dependabot alerts.

Fixes #856, fixes #858, fixes #859 -- bump cryptography and httplib2

---

docs/development/index.rst
docs/development/security.rst

Some of these headers were contributed from Gemeente Haarlem examples.

Documenting security-related headers

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

**Changes**
Update django-loose-fk from 0.7.3 to 0.7.4

Update django-loose-fk to latest version

---

src/openzaak/components/catalogi/admin/besluittype.py
src/openzaak/components/catalogi/admin/catalogus.py
src/openzaak/components/catalogi/admin/forms.py
src/openzaak/components/catalogi/admin/informatieobjecttype.py
src/openzaak/components/catalogi/admin/mixins.py
src/openzaak/components/catalogi/admin/zaaktypen.py
src/openzaak/components/catalogi/tests/admin/test_admin_publish.py
src/openzaak/components/catalogi/tests/admin/test_notifications.py
src/openzaak/components/catalogi/tests/admin/test_zaaktype_admin.py

Fixes #805 
**Changes**
Send notifications for changes in Admin.

Send notifications for Catalogus admin

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/documenten/query/cmis.py
src/openzaak/components/documenten/tests/models/test_human_readable_identification_cmis.py
src/openzaak/utils/tests.py

Fixes #900
The requirements need to be updated once https://github.com/open-zaak/cmis-adapter/pull/50 is released

Fixes #900 - Avoid retrieving zaken

---

src/openzaak/components/documenten/api/serializers.py
src/openzaak/components/documenten/query/cmis.py

Fixes #895 - Performance improvements with CMIS

---

.bumpversion.cfg
CHANGELOG.rst
README.en.md
README.rst
deployment/kubernetes/apps.yml
deployment/single-server/open-zaak.yml
deployment/single-server/requirements.yml
package.json

Prepare 1.3.5 release

---

docs/introduction/open-source/public_code.md

Completes #681.
**Changes**
Added link to the dependencies file from the requirement and changed status to compliant.

Update Document maturity with link to dependencies

---

deployment/requirements.txt
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

**Changes**
* Bumped pygments to mitigate security issue
* Bumped pyyaml to mitigate security issue
We did/do not accept user input, so the vulnerabilities are not likely to affect us in the first place.

Fixes #918, fixes #919, fixes #927 -- Bump pyyaml and pygments

---

.github/workflows/ci.yml
bin/check_requirements.sh
docs/development/howtos/dependencies.rst
docs/development/howtos/index.rst
docs/development/index.rst

**Changes**
Adds a github action job to check that the requirements are properly updated if updated.

add ci requirements action

---

src/openzaak/components/catalogi/tests/admin/test_import_export_zaaktype.py
src/openzaak/components/zaken/api/viewsets.py
src/openzaak/components/zaken/tests/test_zaak_delete_cmis.py
src/openzaak/utils/tests.py

Fixes #951 
:warning: Based on https://github.com/open-zaak/open-zaak/pull/955
:warning: Needs the fix in the cmis-adapter for issue https://github.com/open-zaak/cmis-adapter/issues/52.

Issue #951 - Deleting zaak related to documents (CMIS)

---

.bumpversion.cfg
CHANGELOG.rst
README.en.md
README.rst
deployment/kubernetes/apps.yml
deployment/single-server/open-zaak.yml
package.json

Prepare 1.4.0 release

---

.github/workflows/ci.yml

Only run requirements file checks on branches

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/documenten/api/serializers.py
src/openzaak/components/documenten/models.py
src/openzaak/components/documenten/query/cmis.py

Fixes #974 
The drc-cmis version needs to be updated once this PR is merged and released: https://github.com/open-zaak/cmis-adapter/pull/59

Feature #974 - Additional performance improvements

---

src/openzaak/components/zaken/api/serializers/zaken.py
src/openzaak/utils/validators.py

Fixes part of #985 
Removed a SELECT queries (point 4. in issue) and removed the `getAllVersions` query (point 2. in the issue).

More cmis improvements

---

.gitignore
src/openzaak/conf/includes/base.py
src/openzaak/templates/index.html
src/openzaak/utils/context_processors.py

Fixes #980 
**Changes**
Ensure certain settings are set and exposed by the context processor to properly generate the link in `kanalen_card.html`

Ensure proper settings are exposed for kanalen card.

---

deployment/requirements.in
deployment/requirements.txt
package-lock.json
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Bump dependencies

---

.github/workflows/ci.yml

Should fix detection changes better if the PR is not up to date with the main branch.

Requirements CI action improvement

---

.github/workflows/ci.yml

**Changes**
- Only run Open Zaak test-suite if py/requirements files have changed
- Only run API testplatform tests if py/requirements files have changed
- Only run docker build if py/js/requirements files have changed

Optimize CI

---

src/openzaak/components/catalogi/management/commands/import.py

Was debugging some failing imports and noticed these, might as well just create a PR :-)

Small catalogus import CLI improvements

---

.github/workflows/ci.yml
.gitignore
docker-compose.ci.cmis.yml
src/openzaak/components/documenten/tests/test_auth_cmis.py
src/openzaak/components/documenten/tests/test_eio_delete_cascade_cmis.py
src/openzaak/components/documenten/tests/test_enkelvoudiginformatieobject_cmis.py
src/openzaak/components/documenten/tests/test_objectinformatieobject_cmis.py
src/openzaak/components/documenten/utils.py
src/openzaak/components/zaken/tests/test_auth_cmis.py

Fix clean installation with CMIS_ENABLED=True

---

Dockerfile
src/openzaak/config/admin_urls.py
src/openzaak/config/templates/admin/config_detail.html
src/openzaak/config/tests/test_config_detail.py
src/openzaak/fixtures/default_admin_index.json

Fixes #949
**Changes**
* Fixed a broken link/url reverse in the template leading to a crash
* Added regression test

Fix broken service config page

---

docs/introduction/open-source/public_code.md

**Changes**
Updates the text of the public_code.md to match the minor changes in the 0.2.3 version of the Standard for Public Code.
Co-authored-by: @Ainali

Update Standard for Public Code assessment to 0.2.3

---

CHANGELOG.rst

Fixes #1120
**Changes**
* Added recommendation to flush caches on Open Zaak 1.6.0 upgrade

Added recommendation to flush caches to release notes

---

README.en.md
README.rst
docs/introduction/open-source/public_code.md

Fixes #1129
**Changes**
The test scenario has changed because it contained mistakes, so now URLs
need to be updated.

:alien: [#1129] -- Update api-test.nl badge URLs

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Fixes #1136
**Changes**
Bumped to latest Django security release

:arrow_up: [#1136] -- Bump to Django 3.2.13

---

src/openzaak/tests/test_nginx_error_documents.py
src/openzaak/urls.py
src/openzaak/utils/exceptions.py
src/openzaak/utils/views.py

Fixes #1130
**Changes**
* Added missing errordoc for `/500.json`
* Added missing errordoc for `/413.json`

Add missing error documents

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Related to #1139
**Changes**
* Bumped mozilla-django-oidc
* Bumped mozilla-django-oidc-db

Bump OIDC-related libraries to latest versions

---

src/openzaak/components/catalogi/admin/forms.py
src/openzaak/components/catalogi/api/validators.py
src/openzaak/components/catalogi/tests/admin/test_resultaattype_admin.py
src/openzaak/components/catalogi/validators.py

Fixes #1107
**Changes**
* Refactored admin validation to use same logic as API validation
* Added regression test

Fix incorrect Resultaattype.afleidingswijze_brondatum validation

---

src/openzaak/components/autorisaties/admin_views.py
src/openzaak/components/autorisaties/tests/admin/test_autorisaties_admin.py

Fixes #1080
**Changes**
Fixed collecting the form data if authorizations are specified for objects that don't yet exist.

Fix besluit-authorizations not being displayed

---

.github/workflows/ci.yml
bin/newman_tests.js
bin/postman_tests.sh

Fixes #1099
**Changes**
* Include ZGW OAS tests in CI pipeline

:construction_worker: [#1099] Add ZGW OAS tests to CI pipeline

---

src/openzaak/components/autorisaties/admin_views.py
src/openzaak/components/catalogi/admin/admin_views.py
src/openzaak/components/catalogi/admin/catalogus.py
src/openzaak/components/catalogi/admin/utils.py
src/openzaak/conf/ci.py
src/openzaak/conf/dev.py
src/openzaak/conf/includes/base.py
src/openzaak/templates/admin/catalogi/import_catalogus.html
src/openzaak/templates/admin/catalogi/import_zaaktype.html
src/openzaak/templates/admin/catalogi/select_existing_typen.html
src/openzaak/utils/admin.py

Fixes: https://github.com/open-zaak/open-zaak/issues/1182
**Changes**
* Use requests-cache for zaaktype imports (previously missing)
* Fix the admin layout for custom import pages
* Fix local issue causing all caches to be flushed after performing an import

:bug: [#1182] Fix minor catalogus/zaaktype import issues

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/documenten/query/cmis.py
src/openzaak/components/documenten/tests/test_utils_cmis.py

Fixes https://github.com/open-zaak/cmis-adapter/issues/32
**Changes**
Upgraded drc-cmis
Upgraded pip-tools because of this https://github.com/jazzband/pip-tools/issues/1617

Upgrade drc-cmis + pip-tools

---

src/openzaak/components/catalogi/admin/zaaktypen.py
src/openzaak/components/catalogi/tests/admin/test_zaaktype_admin.py

Fixes #1211
**Changes**
* Fix creating new zaaktype version via the admin

:bug: [#1211] Fix creating new zaaktype version

---

bin/dump_configuration.sh
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Requires https://github.com/maykinmedia/zgw-consumers/pull/44 to be merged and zgw_consumers version to be bumped
Fixes #1215
**Changes**
* Add script to dump config from database

:hammer: [#1215] Add script to dump config from database

---

.github/workflows/code_quality.yml
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/autorisaties/openapi.yaml
src/openzaak/components/autorisaties/swagger2.0.json
src/openzaak/components/catalogi/openapi.yaml
src/openzaak/components/catalogi/swagger2.0.json
src/openzaak/components/zaken/openapi.yaml
src/openzaak/components/zaken/swagger2.0.json

Following #1225, let's have CI check these things.

:construction_worker: Added CI check for missing migrations

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/accounts/tests/test_oidc.py

Fixes #1233
**Changes**
* Fix OIDC session refresh

Issue/1233 OIDC session refresh

---

src/openzaak/components/zaken/api/serializers/zaken.py
src/openzaak/components/zaken/tests/test_zaken.py

Fix incorrect verlenging object

---

src/openzaak/components/catalogi/admin/zaaktypen.py
src/openzaak/components/catalogi/tests/admin/test_zaaktype_admin.py

Fixes #1247 properly
Fixes #1264

:bug: [#1264] Fix saving of published ZaakTypen via admin

---

docs/installation/config/env_config.md
src/openzaak/conf/ci.py
src/openzaak/conf/includes/base.py

Partially addresses #621
**Changes**
* Make NOTIFICATIONS_DISABLED configurable via environment variables

:wrench: [#621] Envvar support for NOTIFICATIONS_DISABLED

---

.bumpversion.cfg
CHANGELOG.rst
README.en.md
README.rst
deployment/kubernetes/apps.yml
deployment/single-server/open-zaak.yml
package-lock.json
package.json
src/openzaak/components/catalogi/admin/zaaktypen.py
src/openzaak/components/catalogi/tests/admin/test_zaaktype_admin.py
src/openzaak/components/zaken/api/serializers/zaken.py
src/openzaak/components/zaken/api/viewsets.py
src/openzaak/utils/filters.py

Release 1.7.4

---

src/openzaak/components/catalogi/admin/zaaktypen.py
src/openzaak/components/catalogi/tests/admin/test_zaaktype_admin.py
src/openzaak/selectielijst/tests/__init__.py
src/openzaak/selectielijst/tests/files/procestypen_2020.json

Fixes #1281
**Changes**
The POST data is now checked first for the specified year which may be different from the configuration default.

Fix selectielijst procestype/year validation issues

---

docs/introduction/open-source/public_code.md

Works towards issue #1261
**Changes**
Updates `public_code.md` to match the 0.4.0 text.
Some new or changed requirements still need to be checked with codebase maintainers.
Co-authored-by: @Ainali

First pass to update Standard for Public Code 0.4.0

---

.github/workflows/ci.yml
docs/openssl.conf
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/catalogi/admin/side_effects.py
src/openzaak/components/catalogi/tests/admin/test_admin_publish.py
src/openzaak/components/catalogi/tests/admin/test_informatieobjecttype_admin.py
src/openzaak/components/catalogi/tests/admin/test_zaaktype_admin.py

regression test to make sure the notification message is correct when the informatiobjecttype is created in the admin

:test_tube: add regression test for iotype admin notification

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Should work as-is, let's see if CI agrees

:arrow_up: Replace vng-api-common with drop-in commonground-api-common

---

src/openzaak/setup.py

Celery initialization appears to trigger setup.py execution multiple times, so it needs to be idempotent.

Fix EXTRA_CERTS_ENVVAR crash due to multiple imports

---

.bumpversion.cfg
CHANGELOG.rst
README.en.md
README.rst
deployment/kubernetes/apps.yml
deployment/single-server/open-zaak.yml
package-lock.json
package.json

:bookmark: Fixes #1313 -- Bump version to 1.8.1 and update changelog

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/conf/dev.py
src/openzaak/conf/includes/base.py

:heavy_plus_sign: [#1310] add Elastic APM

---

src/openzaak/components/besluiten/api/serializers.py
src/openzaak/components/catalogi/api/serializers/eigenschap.py
src/openzaak/components/catalogi/api/serializers/informatieobjecttype.py
src/openzaak/components/catalogi/api/serializers/relatieklassen.py
src/openzaak/components/catalogi/api/serializers/resultaattype.py
src/openzaak/components/catalogi/api/serializers/roltype.py
src/openzaak/components/catalogi/api/serializers/zaaktype.py
src/openzaak/components/documenten/api/serializers.py
src/openzaak/components/zaken/api/serializers/betrokkenen.py
src/openzaak/components/zaken/api/serializers/objecten.py
src/openzaak/components/zaken/api/serializers/zaakobjecten.py
src/openzaak/components/zaken/api/serializers/zaken.py

move changing serializer fields descriptions

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Following dependabot alert
(soundness bug, not remotely exploitable)

Bump cryptography to latest version

---

src/openzaak/components/documenten/api/serializers.py
src/openzaak/components/documenten/tests/test_enkelvoudiginformatieobject.py

fix update documents with empty content

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

:arrow_up: [#1321] bump notificaions-api-common to 0.2.1

---

.bumpversion.cfg
CHANGELOG.rst
README.en.md
README.rst
deployment/kubernetes/apps.yml
deployment/single-server/open-zaak.yml
package-lock.json
package.json
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/documenten/api/serializers.py
src/openzaak/components/documenten/tests/test_enkelvoudiginformatieobject.py
src/openzaak/components/zaken/tests/admin/test_zaak_admin.py
src/openzaak/utils/fields.py

Bugfix release, cherrypicked relevant commits from main

Release 1.8.2

---

docs/development/performance/index.rst
docs/development/performance/notifications.rst

document notification performance test

---

docs/introduction/open-source/public_code.md

Fixes #1349
**Changes**
Updated the requirements.

Update Standard for Public Code assessment to 0.5.0

---

src/openzaak/components/zaken/api/pagination.py
src/openzaak/components/zaken/api/viewsets.py

optimize list zaken 

---

src/openzaak/components/catalogi/api/viewsets/zaaktype.py

Fixes #1370
**Changes**
* Add `deelzaaktypen` to `prefetch_related` for zaaktypen viewset

:zap: [#1370] Optimize zaaktypen list performance with deelzaaktypen prefetch

---

bin/postman_tests.sh
docker/nginx/mocks.conf
fixtures/fixture.json

Fixes #1359 
**Changes**
* Several fixes regarding postman tests (see https://github.com/VNG-Realisatie/gemma-postman-tests/pull/31)
* Added extra required mocks
* Workaround for fixture issues with Selectielijst service

:green_heart: [#1359] Fix ZGW postman tests

---

docs/development/howtos/data_generation.rst
docs/development/howtos/index.rst
fixtures/fixture.json
src/openzaak/management/commands/generate_data.py
src/openzaak/tests/management/test_generate_data.py

 add management command to generate data for testing

---

src/openzaak/components/zaken/api/serializers/zaken.py
src/openzaak/components/zaken/tests/test_zaken.py

fix when zaak.einddatum is earlier than zaak.startdatum

---

docs/development/performance/notifications.rst

by specifying that binary exponential backoff is used
Fixes #1383
**Changes**
* Specify that binary exponential backoff is used for autoretry mechanism

:memo: [#1383] Improve notification autoretry docs

---

src/openzaak/components/zaken/admin/zaken.py
src/openzaak/forms/widgets.py

show map in the admin for Zaak.zaakgeometrie

---

src/openzaak/components/documenten/tests/admin/test_eio_cmis.py
src/openzaak/templates/admin/documenten/cmis.html
src/openzaak/utils/admin.py

Don't show CMIS documents in the admin

---

src/openzaak/components/besluiten/models.py
src/openzaak/components/besluiten/tests/test_auth.py
src/openzaak/utils/query.py

besluiten list api optimization

---

.bumpversion.cfg
CHANGELOG.rst
README.en.md
README.rst
deployment/kubernetes/apps.yml
deployment/single-server/open-zaak.yml
package-lock.json
package.json

:bookmark: release Open Zaak 1.9.0

---

bin/postman_tests.sh
src/openzaak/components/catalogi/api/scopes.py
src/openzaak/components/catalogi/api/serializers/relatieklassen.py
src/openzaak/components/catalogi/api/validators.py
src/openzaak/components/catalogi/api/viewsets/besluittype.py
src/openzaak/components/catalogi/api/viewsets/eigenschap.py
src/openzaak/components/catalogi/api/viewsets/informatieobjecttype.py
src/openzaak/components/catalogi/api/viewsets/relatieklassen.py
src/openzaak/components/catalogi/api/viewsets/resultaattype.py
src/openzaak/components/catalogi/api/viewsets/roltype.py
src/openzaak/components/catalogi/api/viewsets/statustype.py
src/openzaak/components/catalogi/api/viewsets/zaaktype.py
src/openzaak/components/catalogi/openapi.yaml
src/openzaak/components/catalogi/swagger2.0.json
src/openzaak/components/catalogi/tests/test_auth.py

Fixes #1415
depends on https://github.com/VNG-Realisatie/gemma-postman-tests/pull/34

add force-write scope for Catalogi API

---

bin/postman_tests.sh
src/openzaak/components/documenten/api/serializers.py
src/openzaak/components/documenten/tests/test_enkelvoudiginformatieobject.py
src/openzaak/components/documenten/tests/test_validation.py

Fixes #1439
Depends on https://github.com/VNG-Realisatie/gemma-postman-tests/pull/35

make eio.informatieobjecttype mutable

---

src/openzaak/components/documenten/admin.py
src/openzaak/components/documenten/tests/admin/test_eio.py

fix 500 when saving document admin with empty iotype

---

src/openzaak/components/zaken/api/filters.py
src/openzaak/components/zaken/openapi.yaml
src/openzaak/components/zaken/swagger2.0.json
src/openzaak/components/zaken/tests/test_zaak_filter.py

add new zaak query params

---

bin/postman_tests.sh
src/openzaak/components/zaken/api/filters.py
src/openzaak/components/zaken/api/viewsets.py
src/openzaak/components/zaken/openapi.yaml
src/openzaak/components/zaken/swagger2.0.json
src/openzaak/components/zaken/tests/test_zaken.py
src/openzaak/utils/filters.py

Fixes https://github.com/open-zaak/open-zaak/issues/1046
Depends on https://github.com/VNG-Realisatie/gemma-postman-tests/pull/36
Old PR #1068
PR in reference implementation has been merged: https://github.com/VNG-Realisatie/zaken-api/pull/206
**Changes**
* Add extra options for Zaken list ordering: einddatum, publicatiedatum, archiefactiedatum
* Explicitly document these options in the Zaken OAS

Gemeente den haag feature/zaken list sort einddatum rebase

---

src/openzaak/components/zaken/api/serializers/zaken.py
src/openzaak/components/zaken/api/viewsets.py
src/openzaak/components/zaken/openapi.yaml
src/openzaak/components/zaken/swagger2.0.json
src/openzaak/components/zaken/tests/test_zaak_zoek.py
src/openzaak/utils/lookups.py
src/openzaak/utils/serializer_fields.py

add `zaaktype__in`  for zaak__zoek

---

src/openzaak/components/catalogi/api/serializers/eigenschap.py
src/openzaak/components/catalogi/api/serializers/relatieklassen.py
src/openzaak/components/catalogi/api/serializers/resultaattype.py
src/openzaak/components/catalogi/api/serializers/roltype.py
src/openzaak/components/catalogi/api/serializers/statustype.py
src/openzaak/components/catalogi/openapi.yaml
src/openzaak/components/catalogi/resources.md
src/openzaak/components/catalogi/swagger2.0.json
src/openzaak/components/catalogi/tests/test_eigenschap.py
src/openzaak/components/catalogi/tests/test_relatieklassen.py
src/openzaak/components/catalogi/tests/test_resultaattype.py
src/openzaak/components/catalogi/tests/test_roltype.py
src/openzaak/components/catalogi/tests/test_statustype.py

add 'zaaktypeIdentificatie' property to catalogi resources

---

bin/postman_tests.sh
src/openzaak/components/catalogi/api/serializers/zaaktype.py
src/openzaak/components/catalogi/api/validators.py
src/openzaak/components/catalogi/api/viewsets/zaaktype.py
src/openzaak/components/catalogi/models/zaaktype.py
src/openzaak/components/catalogi/openapi.yaml
src/openzaak/components/catalogi/swagger2.0.json
src/openzaak/components/catalogi/tests/test_zaaktype.py

Fixes #1486
Depends on https://github.com/VNG-Realisatie/gemma-postman-tests/pull/41

change unique check for ZaakType

---

.github/workflows/ci.yml

:construction_worker: [#1518] use tar archive of the image for Trivy

---

src/openzaak/templates/master.html

:bug: [#1527] include css styles from commonground-api-common

---

src/openzaak/components/catalogi/admin/forms.py
src/openzaak/components/catalogi/models/mixins.py
src/openzaak/components/catalogi/tests/admin/test_zaaktype_admin.py

Fixes #1474
**Changes**
Catch related object does not exist exception

:bug:[#1474] fix exception thrown with bad catalogus ID

---

src/openzaak/components/documenten/tests/test_validation.py
src/openzaak/components/zaken/tests/test_create.py
src/openzaak/components/zaken/tests/test_validation_zaak.py
src/openzaak/components/zaken/tests/test_zaken.py
src/openzaak/utils/permissions.py

create zaak with incorrect zaaktype

---

src/openzaak/components/catalogi/api/serializers/relatieklassen.py
src/openzaak/components/catalogi/openapi.yaml
src/openzaak/components/catalogi/resources.md
src/openzaak/components/catalogi/swagger2.0.json
src/openzaak/components/catalogi/tests/test_relatieklassen.py

:fire: [#1555] remove ztiot.informatieobjecttype_omschrijving

---

src/openzaak/components/documenten/api/serializers.py
src/openzaak/components/documenten/tests/test_upload.py

:sparkles: [#1550] add 'lock' to BestandsDeel response

---

bin/postman_tests.sh
src/openzaak/components/catalogi/admin/utils.py
src/openzaak/components/catalogi/api/serializers/besluittype.py
src/openzaak/components/catalogi/openapi.yaml
src/openzaak/components/catalogi/resources.md
src/openzaak/components/catalogi/swagger2.0.json
src/openzaak/components/catalogi/tests/test_besluittype.py

Fixes #1558
Depends on https://github.com/VNG-Realisatie/gemma-postman-tests/pull/43

:sparkles: [#1558] make besluittype.zaaktypen read-only

---

src/openzaak/components/catalogi/admin/admin_views.py
src/openzaak/components/catalogi/admin/utils.py
src/openzaak/components/catalogi/tests/admin/test_import_export_zaaktype.py

:sparkles:[#1504] show warning if zaaktype import does nothing

---

docs/installation/config/env_config.md
src/openzaak/templates/admin/object_history.html

Fixes #1571 
Style looks fine.

:fire:[#1571] remove jquery & boostrap from admin history template

---

docs/installation/config/env_config.md
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/zaken/tests/test_zaakinformatieobjecten.py
src/openzaak/components/zaken/tests/utils.py
src/openzaak/conf/includes/base.py

Fixes #1592 
Depends on https://github.com/maykinmedia/django-loose-fk/pull/29

resolve local and external urls with the same host

---

src/openzaak/notifications/migrations/0002_move_config_to_service_model.py

:fore:[#1606] remove default notification service

---

CHANGELOG.rst
SECURITY.rst

:memo:Remove broken link from CHANGELOG.rst

---

src/openzaak/components/autorisaties/forms.py
src/openzaak/components/autorisaties/tests/admin/test_autorisaties_admin.py

:sparkles:[#1584] get autorisaties URL from OPENZAAK_DOMAIN or site

---

src/openzaak/conf/includes/base.py
src/openzaak/tests/test_outgoing_request.py
src/openzaak/utils/apps.py

Fixes #1619
**Changes**
changed User-Agent from requests lib to "Open Zaak"

:sparkles: [#1619] changed user agent to 'Open Zaak'

---

src/openzaak/components/zaken/admin/zaken.py
src/openzaak/components/zaken/models/zaken.py
src/openzaak/components/zaken/tests/admin/test_zaak_admin.py

Fixes #1382
**Changes**
- Added __str__ to zaakkenmerk model
- Added zaakkenmerk as inline to zaak in admin

:sparkles: [#1382] added zaakkenmerk as inline to admin/zaken/zaak

---

docs/api/index.rst
docs/installation/config/cmis.rst
docs/manual/api-authorizations.rst
src/openzaak/tests/test_rewrite_host.py
src/openzaak/utils/middleware.py

fix OPENZAAK_DOMAIN with subpath

---

docs/introduction/upstream-api-parity.rst

Removed a typing error.

---

docs/installation/reference/1-5_upgrade.rst

Corrected some typing errors.

---

docs/manual/catalogi/index.rst

Corrected a typical error.

---

CHANGELOG.rst
src/openzaak/conf/dev.py
src/openzaak/conf/includes/base.py

Fixes #1637
Moved environmental variable to disable 2FA to the base.py

:sparkles: [#1637] added environmental variable to disable 2fa

---

src/openzaak/components/catalogi/admin/besluittype.py
src/openzaak/components/catalogi/admin/informatieobjecttype.py
src/openzaak/components/catalogi/admin/mixins.py
src/openzaak/components/catalogi/tests/admin/test_besluittype_admin.py
src/openzaak/components/catalogi/tests/admin/test_informatieobjecttype_admin.py
src/openzaak/components/catalogi/tests/factories/informatie_objecten.py
src/openzaak/components/catalogi/tests/test_informatieobjecttype.py

:bug:[#1686] fix 500 error when publishing overlapping types

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/conf/ci.py
src/openzaak/conf/includes/base.py
src/openzaak/conf/production.py

partially fixes #1629 
**Changes**
* Refactor settings module to use OAF base settings
Requires https://github.com/maykinmedia/open-api-framework/pull/35 to be merged and released

 🔧 [#1629] Refactor settings module

---

src/openzaak/sass/admin/_admin_theme.scss

fix https://github.com/open-zaak/open-notificaties/issues/150 (Open Zaak part)

:lipstick: fix help text icon layout in the admin

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/besluiten/api/validators.py
src/openzaak/components/documenten/api/validators.py
src/openzaak/components/zaken/api/validators.py
src/openzaak/utils/validators.py

Fixes #1256
Depends on maykinmedia/commonground-api-common#31

:zap:[#1256] remove potential race condition

---

requirements/base.in
requirements/dev.txt
src/openzaak/sass/admin/_admin_theme.scss
src/openzaak/templates/admin/base_site.html

Partially fixes https://github.com/maykinmedia/open-api-framework/issues/21
**Changes**
Reuses the templates from `open-api-framework` to show the version and environment.

[#21] reuse open-api-framework version/environment templates

---

.github/workflows/code_quality.yml

Partially fixes https://github.com/maykinmedia/open-api-framework/issues/17
**Changes**
Merges the CI steps which checks for uncommitted OAS changes.

[#17] merge CI OAS check steps

---

docker-compose.yml

[#1721] respect DISABLE_2FA envvar in docker-compose

---

src/openzaak/components/zaken/admin/zaken.py
src/openzaak/components/zaken/tests/admin/test_zaak_admin.py

Fixes https://github.com/open-zaak/open-zaak/issues/1703
**Changes**
Adds filtering zaken on RSIN or BSN in the admin.

[#1703] add zaak filtering on BSN/RSIN

---

src/openzaak/components/zaken/admin/zaken.py
src/openzaak/components/zaken/tests/admin/test_zaak_admin.py

Fixes #1064 
**Changes**
Shows the status, zaaktype and resultaat in the admin list view voor zaken.

[#1064] show status, zaaktype and resultaat for zaken

---

docs/installation/reference/import.rst

Fixes https://github.com/open-zaak/open-zaak/issues/1687
**Changes**
Updates the bulk import documentation about notifications.

[#1687] update bulk import documentation

---

src/openzaak/fixtures/default_admin_index.json
src/openzaak/utils/admin.py

Fixes #1568
**Changes**
Added Audit Trail to the admin dashboard:
list_display additions: resource and actie
list_filter additions: resource and actie
set the change and list permissions to false

:sparkles: [#1650] added audit trail to admin

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/conf/dev.py

Fixes #1695
**Changes**
- Fixed the main issue of the redirect_to func not working
- Fixed bonus mention of being logged out after django updates during development

:arrow_up: [#1695] updated maykin-2fa

---

src/openzaak/components/zaken/tests/test_pagination.py
src/openzaak/conf/includes/base.py
src/openzaak/utils/pagination.py

Fixes #1574
**NOTE**: the results of performance testing this branch are added to the bitbucket

:zap:[#1574] Copy FuzzyPagination from #1368

---

docs/installation/config/openzaak_config.rst

update documentation for OZ and ON configuration

---

Dockerfile
bin/celery_worker.sh
bin/check_celery_worker_liveness.py
docker-compose.yml
src/openzaak/celery.py

Fixes #1727 partially
**Changes**
* Add healthchecks for celery

:stethoscope: [#1727] Celery healthchecks

---

src/openzaak/management/commands/generate_data.py

Fixes #1732
**Changes**
Added also archiefnominatie to the test data

:sparkles: Add archiefnominatie to test data

---

deployment/requirements.txt
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Fixes [#50](https://github.com/maykinmedia/open-api-framework/issues/50)
**Changes**
- certifi `2024.7.22` to `2024.7.4`
- idna `3.4` to `3.7`
- jinja2 `3.1.2` to `3.1.4`
- urllib3 `1.26.18` to `1.26.19`

:arrow_up: [#50] updated deployment packages

---

.bumpversion.cfg
CHANGELOG.rst
README.en.md
README.rst
deployment/kubernetes/apps.yml
deployment/single-server/open-zaak.yml
package-lock.json
package.json
publiccode.yaml

Fixes https://github.com/maykinmedia/objects-api/issues/436 (OZ part)

:bookmark: release 1.14.0

---

src/openzaak/components/autorisaties/forms.py
src/openzaak/components/autorisaties/tests/admin/test_autorisaties_admin.py

autorisatie with manual iotypen

---

src/openzaak/conf/includes/api.py

Fixes #1780 
**Changes**
* Fix setting NOTIFICATIONS_DISABLED via envvar

:bug: [#1780] Fix setting NOTIFICATIONS_DISABLED via envvar

---

.github/workflows/ci.yml
bin/generate_envvar_docs.sh
docs/installation/config/env_config.rst
docs/installation/reference/import.rst
src/openzaak/conf/dev.py
src/openzaak/conf/includes/base.py
src/openzaak/conf/production.py
src/openzaak/templates/open_api_framework/env_config.rst

Fixes https://github.com/open-zaak/open-zaak/issues/1649 partially
**Changes**
* Document the envvars
* Add CI job to check if envvar docs were updated

📝 [#1649] Document envvars

---

deployment/single-server/vars/open-zaak.example.yml
docs/installation/code/env
docs/installation/config/env_config.rst
docs/installation/kubernetes.rst
docs/installation/single_server.rst
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/conf/includes/api.py
src/openzaak/conf/includes/base.py

Fixes maykinmedia/open-api-framework#68
Also fixes:  maykinmedia/mozilla-django-oidc-db#116

:wrench:[maykinmedia/open-api-framework#68] fix CSP errors

---

.github/workflows/ci.yml

Partially fixes https://github.com/maykinmedia/objects-api/issues/463

Disable trivy image scan

---

docs/development/performance/index.rst
docs/manual/oidc.rst

Fixes #1785 
**NOTE**: This PR includes only system requirements update, all experimental performance tests are not supposed to be included into the documentation

update performance documents

---

src/openzaak/components/documenten/api/filters.py
src/openzaak/components/documenten/openapi.yaml
src/openzaak/components/documenten/tests/test_filters.py

Fixes #1774 
**Changes**
* Add EnkelvoudigInformatieObject.trefwoorden__overlap filter

:sparkles: [#1774] Add EnkelvoudigInformatieObject.trefwoorden__overlap filter

---

src/openzaak/components/zaken/api/serializers/zaken.py
src/openzaak/components/zaken/openapi.yaml
src/openzaak/components/zaken/tests/test_zaak_zoek.py
src/openzaak/utils/lookups.py

Fixes #1783
**Changes**
* Add zaaktype__not_in filter to ZaakZoek

✨ [#1783] Add zaaktype__not_in filter to ZaakZoek

---

src/openzaak/components/catalogi/admin/resultaattype.py
src/openzaak/management/commands/generate_data.py
src/openzaak/tests/management/test_generate_data.py

fix resultaattype.resultaattypeomschrijving for generation data

---

src/openzaak/components/autorisaties/admin.py
src/openzaak/components/autorisaties/migrations/0014_remove_orphaned_jwtsecrets.py
src/openzaak/components/autorisaties/tests/admin/test_applications_admin.py
src/openzaak/components/autorisaties/tests/test_migrations.py

[#1741] delete jwtsecret when deleting applicatie in the admin

---

CHANGELOG.rst
docs/installation/config/env_config.rst
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/zaken/tests/test_create.py
src/openzaak/components/zaken/tests/test_notifications_send.py
src/openzaak/conf/includes/base.py
src/openzaak/config/tests/bootstrap/test_notifications_api_configuration.py
src/openzaak/fixtures/default_admin_index.json
src/openzaak/selectielijst/tests/test_paginated_resultaten.py

Fixes #1817
Do note that updating the fixture is still necessary: "SessionProfile admin should be added to admin index and its fixture."

[#1817] Update open-api-framework

---

docs/installation/config/env_config.rst
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

:arrow_up:[#1802] update to open-api-framework 0.9.1

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Fixes maykinmedia/open-api-framework#93 partially
**Changes**
* Security updates

:arrow_up: [maykinmedia/open-api-framework#93] Security updates

---

docker-compose.yml
docker/setup_configuration/data.yaml
docker/setup_configuration/data.yml
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/autorisaties/openapi.yaml
src/openzaak/components/besluiten/openapi.yaml
src/openzaak/components/catalogi/openapi.yaml
src/openzaak/components/documenten/openapi.yaml
src/openzaak/components/zaken/openapi.yaml
src/openzaak/conf/includes/base.py
src/openzaak/utils/exceptions.py
src/openzaak/utils/schema.py

Fixes #1825
~~Depends on https://github.com/maykinmedia/commonground-api-common/pull/59~~
~~Depends on https://github.com/maykinmedia/commonground-api-common/pull/56~~
~~Depends on https://github.com/open-zaak/open-zaak/pull/1844~~

:sparkles: [#1825] add yaml config for authorization configuration step

---

.bumpversion.cfg
CHANGELOG.rst
README.en.md
README.rst
deployment/kubernetes/apps.yml
deployment/single-server/open-zaak.yml
docs/development/performance/index.rst
package-lock.json
package.json
publiccode.yaml
src/openzaak/__init__.py

:bookmark:release 1.17.0

---

docker/setup_configuration/data.yaml
docs/installation/config/openzaak_config_cli.rst
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/conf/includes/base.py

~~Based on #1844, should be merged first~~
Fixes maykinmedia/open-api-framework#23
Fixes #1822

OIDC setup configuration

---

src/openzaak/conf/includes/base.py

Fixes #1832
Map on Zaak Admin change view should now work

:bug:[#1832] fix map view to CSP headers

---

docs/client-development/authentication.rst
src/openzaak/components/zaken/api/mixins.py
src/openzaak/components/zaken/api/serializers/zaken.py
src/openzaak/components/zaken/api/viewsets.py
src/openzaak/components/zaken/openapi.yaml
src/openzaak/components/zaken/tests/test_rol_update.py

add PUT endpoint for rollen

---

docs/client-development/authentication.rst
docs/conf.py
src/openzaak/components/zaken/openapi.yaml

Fixes #1873 
**Changes**
* Regenerate Zaken API schema
* Add jwt.io to linkcheck_ignore to fix build

:memo: [#1826] Regenerate Zaken API schema

---

src/openzaak/components/zaken/api/viewsets.py
src/openzaak/components/zaken/openapi.yaml
src/openzaak/components/zaken/tests/test_audittrails.py

:sparkles:[#1581] add audit trail for zaakobject delete

---

.github/pull_request_template.md

to make sure experimental features are documented in the PRs in which they are introduced

:memo: Checkboxes for experimental features in PR template

---

docs/api/experimental.rst
docs/api/index.rst

:memo: [#1854] document experimental features

---

.github/ISSUE_TEMPLATE/prepare-release.md

**Changes**
* Add prepare release issue template
**Checklist**

:wrench: Add prepare release issue template

---

.github/workflows/quick-start.yml

Fixes [maykinmedia/open-api-framework#101]

[maykinmedia/open-api-framework#101] Add quick-start.yml

---

.github/ISSUE_TEMPLATE/prepare-release.md

Closes maykinmedia/open-api-framework#107 partially
**Changes**
* Add dep updates to release template
**Checklist**

:memo: [maykinmedia/open-api-framework#107] Add dependency updates to release template

---

src/openzaak/components/zaken/api/serializers/zaken.py
src/openzaak/components/zaken/brondatum.py
src/openzaak/components/zaken/tests/test_zaak_archive.py
src/openzaak/components/zaken/tests/utils.py

[#1812] Auto fill in zaak.startdatum_bewaartermijn

---

src/openzaak/components/zaken/tests/test_zaakobject_zaakobjecttype.py
src/openzaak/config/tests/test_feature_flags.py

Closes #1915
**Changes**
* Fix flaky tests
**Checklist**

:white_check_mark: [#1915] Fix flaky tests

---

requirements/ci.txt
requirements/dev.txt
src/openzaak/utils/serializer_fields.py

Closes #1906 
**Changes**
* Upgrade flake8 to 7.1.2
**Checklist**

 ⬆️ [#1906] Upgrade flake8 to 7.1.2

---

docs/installation/config/env_config.rst
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/conf/includes/base.py

**Changes**
* Upgrade open-api-framework to 0.9.3
**Checklist**

:arrow_up: [#1917] Upgrade open-api-framework to 0.9.3

---

.github/workflows/quick-start.yml
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

⬆️ [#1917] Upgrade python deps to fix vulnerabilities

---

.bumpversion.cfg
CHANGELOG.rst
README.en.md
README.rst
deployment/kubernetes/apps.yml
deployment/single-server/open-zaak.yml
docs/development/performance/index.rst
package-lock.json
package.json
publiccode.yaml
src/openzaak/__init__.py
src/openzaak/conf/locale/nl/LC_MESSAGES/django.po

Closes #1917
**Changes**
* Release version 1.19.0
**Checklist**

 🔖 [#1917] Release version 1.19.0

---

.github/workflows/oas-check.yml
bin/generate_schema_for_component.sh

to verify that the schema is up to date
Closes https://github.com/maykinmedia/open-api-framework/issues/115 partially
**Changes**
* Always run OAS check
**Checklist**

:construction_worker: [maykinmedia/open-api-framework#115] Always run OAS check

---

.bumpversion.cfg
CHANGELOG.rst
README.en.md
README.rst
deployment/kubernetes/apps.yml
deployment/single-server/open-zaak.yml
package-lock.json
package.json

:bookmark: Release version 1.9.1

---

src/openzaak/components/catalogi/models/roltype.py
src/openzaak/components/catalogi/tests/models/test_roltype.py

Closes #1949
**Changes**
Add validation for zaaktype

[#1949] Roltype toevoegen bij opslaan en nieuwe toevoegen geeft foutmelding

---

src/openzaak/fixtures/default_groups.json

Closes #1973
**Changes**
Add permissions for view and delete sessionprofile

Issue/1973 Default admin groups currently don't have the session profile read+delete rights

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/autorisaties/api/filters.py
src/openzaak/components/besluiten/api/filters.py
src/openzaak/components/catalogi/api/filters.py
src/openzaak/components/documenten/api/filters.py
src/openzaak/utils/filterset.py

Fixes [maykinmedia/open-klant#341]

:art: [maykinmedia/open-klant#341] Fix help_text field in FilterSet

---

src/openzaak/utils/query.py

Closes #1937 partially
Ran this on the testenvironment and noticed a 5-10% speedup for the zaken list endpoint when doing concurrent testing. Comparing the query plans also point out that this change makes the database query more performant.
Baseline: https://github.com/open-zaak/open-zaak/actions/runs/14469538342/job/40579723875#step:4:755
After changes: https://github.com/open-zaak/open-zaak/actions/runs/14510298039/job/40707299988?pr=1993#step:4:755
**Changes**
* Avoid duplicate WHEN/THEN clauses in authorizations filtering
**Checklist**

:zap: [#1937] Avoid duplicate WHEN/THEN clauses in authorizations filtering

---

.github/workflows/ci.yml
bin/compile_dependencies.sh
requirements/ci.txt
requirements/dev.txt
requirements/performance-tests.in
requirements/test-tools.in

**Changes**
* Only install necessary pytest deps for performance tests
**Checklist**

:construction_worker: Only install necessary pytest deps for performance tests

---

docs/api/experimental.rst
src/openzaak/components/catalogi/admin/roltype.py
src/openzaak/components/catalogi/api/filters.py
src/openzaak/components/catalogi/openapi.yaml
src/openzaak/components/catalogi/tests/test_roltype.py

Closes #1933
**Changes**
Added filter to roltype omschrijving

feature/1933 List all roltype by roltypeOmschrijving

---

performance_test/test_zaken_list.py
src/openzaak/management/commands/generate_data.py
src/openzaak/tests/management/test_generate_data.py

to verify later whether indexes on auth related fields boost performance for this
**Changes**
* Add performance test with credentials with few authorized types
**Checklist**

:white_check_mark: Add performance test with credentials with few authorized types

---

src/openzaak/utils/expansion.py

Closes #1837
**Changes**
- moves _nodes list initialization to `__init__`.
**Checklist**

:bug: [#1837] Fix memory retention caused by expand parameter

---

.bumpversion.cfg
CHANGELOG.rst
README.en.md
README.rst
deployment/kubernetes/apps.yml
deployment/single-server/open-zaak.yml
docs/conf.py
docs/development/performance/index.rst
docs/installation/prerequisites.rst
package-lock.json
package.json
publiccode.yaml
requirements/dev.in
requirements/dev.txt
src/openzaak/__init__.py
src/openzaak/conf/locale/nl/LC_MESSAGES/django.po

Closes #2006
**Changes**
* Add missing bump-my-version to dev dependencies
* Release version 1.21.0
**Checklist**

 🔖 [#2006] Release version 1.21.0

---

src/openzaak/components/documenten/api/serializers.py
src/openzaak/components/documenten/tests/test_enkelvoudiginformatieobject.py

Closes #2030 
**Changes**
When patching the enkelvoudiginformatieobjecten the ondertekening gets reset. 
This update fixes the bug so that patching the object no longer resets or removes the ondertekening field.
**Checklist**

:bug: [#2030] bug fix ondertekening gets reset

---

.github/workflows/ci.yml
docs/installation/config/env_config.rst
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/accounts/tests/test_oidc.py
src/openzaak/conf/includes/base.py

Closes #1852
**Changes**
Add connection pooling
**Checklist**

:sparkles: [#1852] add connection pooling

---

src/openzaak/sass/admin/_admin_theme.scss
src/openzaak/sass/admin/_app_overrides.scss
src/openzaak/sass/admin/_vars.scss
src/openzaak/sass/admin/themes/_dark.scss
src/openzaak/sass/admin/themes/_light.scss
src/openzaak/templates/admin/base.html
src/openzaak/templates/admin/base_site.html

Closes maykinmedia/open-api-framework#149 partially
**Changes**
* Fix light/dark themes for admin UI
* Add missing theme toggle in admin UI
* Changes the light admin theme to be the same as other components
**Checklist**

:bug: [maykinmedia/open-api-framework#149] Add missing theme toggle in admin UI

---

bin/celery_worker.sh

Done as part of https://github.com/maykinmedia/charts/issues/165

:fire: Remove unused command line args

---

src/openzaak/components/zaken/api/serializers/zaken.py
src/openzaak/components/zaken/api/viewsets.py
src/openzaak/components/zaken/models/identification.py
src/openzaak/components/zaken/openapi.yaml
src/openzaak/components/zaken/tests/test_zaken.py

Closes #2020
**Changes**
**Checklist**

:sparkles: [#2020] implement bulk reserving of zaaknummers

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/autorisaties/middleware.py
src/openzaak/components/autorisaties/tests/test_jwt.py
src/openzaak/components/documenten/tests/test_auth.py
src/openzaak/components/zaken/api/permissions.py
src/openzaak/import_data/permissions.py
src/openzaak/utils/permissions.py

Closes #635
**Changes**
**Checklist**

:white_check_mark: [#635] move jwt expiry validation to common-ground-api-common

---

src/openzaak/components/autorisaties/openapi.yaml
src/openzaak/components/besluiten/openapi.yaml
src/openzaak/components/catalogi/openapi.yaml
src/openzaak/components/documenten/openapi.yaml
src/openzaak/components/zaken/api/viewsets.py
src/openzaak/components/zaken/openapi.yaml
src/openzaak/conf/includes/api.py

:bug: [#2085] Fixed read_only fields as required in api schema

---

src/openzaak/components/zaken/api/serializers/zaken.py
src/openzaak/components/zaken/tests/test_hoofdzaak_afsluiting.py

Closes #2098
**Changes**
...
**Checklist**

:bug: [#2098] fix error when deelzaak changes status without resultaat

---

src/openzaak/management/commands/generate_data.py
src/openzaak/tests/management/test_generate_data.py

previously only autorisaties for Zaak related resources were created
**Changes**
* Generate autorisaties for all APIs via generate_data command
**Checklist**

:sparkles: Generate autorisaties for all APIs via generate_data command

---

docs/manual/logging.rst
src/openzaak/components/autorisaties/api/viewsets.py
src/openzaak/components/besluiten/api/viewsets.py
src/openzaak/components/catalogi/api/viewsets/besluittype.py
src/openzaak/components/catalogi/api/viewsets/catalogus.py
src/openzaak/components/catalogi/api/viewsets/eigenschap.py
src/openzaak/components/catalogi/api/viewsets/informatieobjecttype.py
src/openzaak/components/catalogi/api/viewsets/relatieklassen.py
src/openzaak/components/catalogi/api/viewsets/resultaattype.py
src/openzaak/components/catalogi/api/viewsets/roltype.py
src/openzaak/components/catalogi/api/viewsets/statustype.py
src/openzaak/components/catalogi/api/viewsets/zaakobjecttype.py
src/openzaak/components/catalogi/api/viewsets/zaaktype.py
src/openzaak/components/documenten/api/viewsets.py
src/openzaak/components/zaken/api/viewsets.py
src/openzaak/utils/__init__.py

Closes #2058 
**Changes**
* Add logging events for operations on all API endpoints
**Checklist**

✨ [#2058] Add logging events for operations on all API endpoints

---

src/openzaak/conf/includes/base.py

Verified that it works on k8s:
Closes #2088
**Changes**
* Workaround to fix APM for psycopg pooling
**Checklist**

:bug: [#2088] Workaround to fix APM for psycopg pooling

---

src/openzaak/components/zaken/tests/assertions.py
src/openzaak/components/zaken/tests/test_zaak_closed.py

Closes #2110 
Fixed tests, with all operations
**Changes**
**Checklist**

[#2110] :white_check_mark: Fix tests for ClosedZaakMixin

---

.github/workflows/ci.yml

Closes maykinmedia/open-api-framework#114
**Changes**
* Upload performance tests results to bencher
**Checklist**

:construction_worker: [maykinmedia/open-api-framework#114] Upload performance tests results to bencher

---

.github/ISSUE_TEMPLATE/prepare-release.md
docs/development/performance/index.rst

Closes #2148 partially
**Changes**
* Use k8s environment for performance testing
**Checklist**

:memo: [#2148] Use k8s environment for performance testing

---

bin/docker_start.sh

Closes maykinmedia/open-api-framework#85
**Changes**
**Checklist**

:sparkles: [maykinmedia/open-api-framework#85] set UWSGI_THREADS to 4

---

docs/api/experimental.rst
src/openzaak/components/catalogi/api/filters.py
src/openzaak/components/catalogi/api/viewsets/zaakobjecttype.py
src/openzaak/components/catalogi/openapi.yaml
src/openzaak/components/catalogi/tests/test_zaakobjecttype.py

Closes #2178
**Changes**
**Checklist**

:sparkles: [#2178] Add status query param to zaakobjecttypen
