src/openzaak/components/catalogi/models/validators.py

The regex in:
letters_numbers_underscores_validator
looks like it was copy-pasted from:
letters_numbers_underscores_spaces_validator
This commit removes the space as a valid character from
the letters_numbers_underscores_validator.
Addresses: https://github.com/open-zaak/open-zaak/issues/66

Remove unwanted space from valid characters list

---

README.rst

Switched from British to American spelling to match filename.

Fix broken link to license.md

---

src/openzaak/components/besluiten/tests/test_validation.py
src/openzaak/components/documenten/tests/test_validation.py
src/openzaak/components/zaken/tests/test_validation.py
src/openzaak/utils/serializer_fields.py

... for urls linked to the resources of other internal APIs (components)
Issue - https://github.com/open-zaak/open-zaak/issues/77

Replace 'no_match' to 'bad-url'

---

src/openzaak/components/documenten/api/viewsets.py

because otherwise get_serializer_class that is called by notifications when creating i.e. `Gebruiksrechten` will fail

Fixed issue with get_serializer_class for EIO viewset without action

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

fixes https://github.com/open-zaak/open-zaak/issues/99 because https://github.com/VNG-Realisatie/vng-api-common/commit/bd9a716a5417469b8fb8f2dc61370466107cdc56 is in this version of vng-api-common

Bump vng-api-common to 1.0.22

---

src/openzaak/components/zaken/api/viewsets.py

Issue - #154
DB queries reduction:
1. Zaken component 
* GET `/zaken/api/v1/zaakeigenschappen` (for 5 observations)
before: 22
after: 12
* GET `/zaken/api/v1/klantcontacten` (for 100 observations)
before: 107
after: 7

optimize db queries - part 3 (zaken component)

---

src/openzaak/components/catalogi/api/viewsets/besluittype.py
src/openzaak/components/catalogi/api/viewsets/catalogus.py
src/openzaak/components/catalogi/api/viewsets/eigenschap.py
src/openzaak/components/catalogi/api/viewsets/informatieobjecttype.py
src/openzaak/components/catalogi/api/viewsets/relatieklassen.py
src/openzaak/components/catalogi/api/viewsets/resultaattype.py
src/openzaak/components/catalogi/api/viewsets/roltype.py

Issue - #154
DB queries reduction (for 100 observations):
`Catalogi` component:
GET `/zaken/api/v1/besluittypen`
before: 306
after: 8
GET `/zaken/api/v1/catalogussen` (for 10 observations)
before: 36
after: 9
GET `/zaken/api/v1/eigenschappen`
before: 106
after: 6
GET `/zaken/api/v1/informatieobjecttypen`
before: 106
after: 6
GET `/zaken/api/v1/zaaktype-informatieobjecttypen`
before: 206
after: 6
GET `/zaken/api/v1/resultaattypen`
before: 106
after: 6
GET `/zaken/api/v1/roltypen`:
before: 106
after: 6

optimize db queries - part 4 (catalogi component)

---

src/openzaak/components/documenten/models.py
src/openzaak/components/zaken/api/serializers/zaken.py
src/openzaak/components/zaken/api/validators.py
src/openzaak/components/zaken/loaders.py
src/openzaak/components/zaken/tests/test_validation.py
src/openzaak/components/zaken/tests/test_zaak_archive.py
src/openzaak/loaders.py
src/openzaak/utils/validators.py

Given that an OpenZaak ZAAK is related with a document from somewhere else, the following validations now happen conform ZGW standard:
* when a case is being closed:
* all documents must have `indicatieGebruiksrecht` set to either `false` or `true`
* all documents must be unlocked
* when a ZAAK is being archived, all documents must be archived prior to that
The implementation has moved the validation code from the serializer level (`validate` method) into three validator classes.

Fixes #128 -- Validate external informatieobjecten

---

fixtures/fixture.json

to ensure that it's possible to fetch local object by url in validators

Added APICredential and Applicatie to fixtures for newman tests

---

.travis.yml
src/openzaak/components/documenten/models.py
src/openzaak/components/documenten/tests/admin/test_eiocanonical_inline_audittrail.py

Saw some examples with `script` empty for a no-op, and Travis docs explicitly mention you're not allowed to use `exit`

Another attempt at fixing the Travis deploy step

---

src/openzaak/components/catalogi/admin/forms.py

The field is a dynamic-arrayfield in the admin, so no need to use
comma's for value-separation. Removed the help text to remove confusion.

Remove added help text

---

src/openzaak/conf/includes/api.py

The previous commit pointed to DRC 1.1 schema, while we must check
against 1.0 schema. Took the latest commit from the master branch.

Fix reference to DRC API schema

---

src/openzaak/conf/includes/api.py

because they were pointing to the develop branches, which track 1.1 features

Fixed ZRC and ZTC api spec references to point to 1.0.x

---

src/openzaak/components/zaken/api/viewsets.py
src/openzaak/conf/dev.py

Ordering is relevant for pagination & it silences the warnings in the test output.
Dev settings are modified to hard-error when you forget to specify the ordering on viewset querysets.

Specify viewset queryset ordering

---

src/openzaak/components/catalogi/admin/forms.py

The field is not present on the model form if you only have read-only permissions, which crashes with:
```
2020-01-07 10:52:14,177 ERROR django.request log 10 140085638494080  Internal Server Error: /admin/catalogi/zaaktype/12/change/
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
response = get_response(request)
File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File …
```

Ensure admin doesn't crash if you have readonly permissions

---

requirements/ci.txt
requirements/dev.txt

Replaces #376 -- bumps waitress in dev/CI environment.
This is not really critical since waitress is not used for production
usage, but dependabot will probably keep sending PRs for it.

Bump waitress to 1.4.2

---

.travis.yml
bin/postman_tests.sh

Via #379 it became clear that forks (untrusted) do not have access
to the necessary environment variables to:
* run Newman tests
* publish docker images
This should disable the relevant stages for forks, keeping the Django
tests and code style checks stage. Newman tests and docker builds/push
will happen once the branch is merged into master.
Note that this introduces a small regression risk - changes could be
introduced that break the API tests from the ATP and we'd only
realize _after_ the merge to master.

Make Newman/Docker stages conditional

---

.bumpversion.cfg
.dockerignore
CHANGELOG.rst
Dockerfile
README.rst
deployment/kubernetes/apps.yml
deployment/kubernetes/roles/openzaak/defaults/main.yml
deployment/single-server/roles/openzaak/defaults/main.yml
deployment/single-server/roles/openzaak/tasks/containers.yml
docs/development/changelog.rst
docs/development/index.rst
docs/development/release.rst
docs/installation/deployment/kubernetes.rst
docs/installation/deployment/single_server.rst
docs/installation/index.rst
docs/installation/updating.rst
package-lock.json
package.json
requirements/dev.in
requirements/dev.txt
setup.cfg

* Document upgrade on K8s and single server
* Applied Docker image/git tag versioning
* Added bumpversion & synced version numbers everywhere
* Documented release process w/r to versioning

Fixes #360 -- Document how to upgrade Open Zaak

---

package.json
src/openzaak/components/besluiten/api/viewsets.py
src/openzaak/components/zaken/api/exceptions.py
src/openzaak/components/zaken/api/mixins.py
src/openzaak/components/zaken/api/viewsets.py
src/openzaak/components/zaken/models/zaken.py
src/openzaak/components/zaken/openapi.yaml
src/openzaak/components/zaken/resources.md
src/openzaak/components/zaken/swagger2.0.json
src/openzaak/components/zaken/tests/factories.py
src/openzaak/components/zaken/tests/test_amsterdam_overlast_water.py
src/openzaak/components/zaken/tests/test_notifications_send.py
src/openzaak/components/zaken/tests/test_zaak_archive.py
src/openzaak/components/zaken/tests/test_zaak_closed.py

Changing of Zaak data is not allowed if the Zaak is closed. This extends to related objects:
However, the updates are allowed if you have the scope `zaken.geforceerd-bijwerken`.

Fixes #298 -- block zaak data mutations if the zaak is closed

---

src/openzaak/components/autorisaties/api/schema.py
src/openzaak/components/besluiten/api/schema.py
src/openzaak/components/besluiten/openapi.yaml
src/openzaak/components/besluiten/swagger2.0.json
src/openzaak/components/catalogi/api/schema.py
src/openzaak/components/documenten/api/schema.py
src/openzaak/components/documenten/openapi.yaml
src/openzaak/components/documenten/swagger2.0.json
src/openzaak/components/zaken/api/schema.py
src/openzaak/components/zaken/openapi.yaml
src/openzaak/components/zaken/swagger2.0.json
src/openzaak/components/zaken/tests/test_auth.py
src/openzaak/conf/includes/api.py
src/openzaak/conf/includes/base.py
src/openzaak/management/commands/generate_swagger_component.py
src/openzaak/tests/api_strategy/test_api_versioning.py
src/openzaak/utils/middleware.py

* Each API has a (potentially) different patch version
* Ensure the API version header is correctly returned
* Ensure the API version is correctly reflected in the API spec

Provide individual API versions for each API

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

New version works with latest setuptools, which fixes the docker image
build.
Required to make #491 and #499 pass

Bump MarkupSafe version

---

deployment/single-server/nlx.yml

The previous var-override for `nlx_txdb_migrations_image` was not picked up.
When moving `nlx_txdb_migrations_image` to the role-level, it worked.

Moved NLX txdb migration image var to role

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

This version supports the toggle to not sync user groups. In certain
cases, the group claim is not included, leading to a reset of the user
groups. Disabling group sync prevents this reset.

Bump django-auth-adfs-db version

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/catalogi/tests/test_zaaktype.py

Fixes #544 
**Changes**
* added a test for bug that occurred when creating a Zaaktype via the API without referentieproces.link (which should be optional)

Added test for creating Zaaktype without referentieproces.link

---

src/openzaak/components/catalogi/models/eigenschap.py

Fixes #553 
**Changes**
* set `blank=False` for Eigenschap.specificatie_van_eigenschap

Fixes #553 -- made Eigenschap.specificatie required in admin

---

bin/docker_start.sh
default.conf
docker-compose.yml
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/conf/includes/base.py
src/openzaak/conf/production.py
src/openzaak/management/commands/generate_swagger_component.py

Fixes #559 
**Changes**
* Let uwsgi handle the `SCRIPT_PATH` machinery
* Added sample nginx/docker-compose config
* Bumped vng-api-common with bugfix where the `script_prefix` is stripped from the path to resolve to a viewset, tests are added to vng-api-common.
How to test:
```bash
SUBPATH=/openzaak docker-compose up --build
```
Navigate to http://localhost:9000/openzaak/ and verify that everything works.

Fix Open Zaak running on a subpath

---

src/openzaak/components/catalogi/api/serializers/eigenschap.py
src/openzaak/components/catalogi/tests/factories/eigenschap.py
src/openzaak/components/catalogi/tests/test_eigenschap.py

Fixes #562 
**Changes**
Removed the `read_only` status of `Eigenschap.specificatie`. The object _is_ included in the API spec for the writable body, and it's the only way to specify the spec in the API.

Don't ignore nested eigenschapspecificatie

---

docs/development/getting_started.rst
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Fixes #585
**Changes**
Updated `pip-tools` to 5.2.1. This will require `pip>=20.0`.
NOTE: Apologies for the changed format of requirements. This is caused by the new pip tools version.

Fixes #585 - Updated pip tools and set minimum pip version.

---

docs/installation/configuration.rst

Use Service model instead of APICredential
**Changes**
* Updated the configuration documentation to use `Service` instead of `External API Credential`

Updated OZ config documentation

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

PR #634 and #630 fix security vulnerabilities in our depencies used. This PR bundles them using our pip-tools stack.

Bump django-sendfile2 and httplib

---

.bumpversion.cfg
README.en.md
README.rst
deployment/kubernetes/apps.yml
deployment/single-server/open-zaak.yml
docs/development/releasing.rst
package-lock.json
package.json
src/openzaak/components/zaken/api/filters.py
src/openzaak/components/zaken/openapi.yaml
src/openzaak/components/zaken/swagger2.0.json
src/openzaak/components/zaken/tests/test_zaken.py
src/openzaak/utils/filters.py

Fixes #591
**Changes**
* implemented the `maxVertrouwelijkheidaanduiding` filter on the `zaak-list` operation
* implemented the `betrokkene*` filters on the `zaak-list` operation

Implement new filters in API standard

---

src/openzaak/components/catalogi/admin/forms.py

Fixes #520
**Changes**
The upstream standard relaxed validation in case that no 'procestermijn' is
specified for a given Selectielijst resultaat, see
https://github.com/VNG-Realisatie/gemma-zaken/pull/1596/files.
This patch relaxes that validation in the Open Zaak admin.
The API aspect of this change was already implemented in 6e38b865c.

Relax Resultaat.afleidingswijze validation

---

deployment/single-server/README.md

Updated readme to note Ansible-galaxy roles and collections need to be installed separately

Updated readme to note Ansible-galaxy roles and collections

---

deployment/requirements.txt
requirements/dev.in
requirements/dev.txt

Latest Ansible & Kubernetes package versions.
**Changes**
* Updated the packaged/bundled deployment deps to latest minor/patch releases
* Deployed Open Zaak 1.3.1 to https://test.openzaak.nl
* Included deployment deps into `requirements/dev.in` so we get all dev and deployment deps in `requirements/dev.txt`

Bump deployment dependencies

---

src/openzaak/components/documenten/api/serializers.py
src/openzaak/components/documenten/tests/test_enkelvoudiginformatieobject.py

Fixes #608 
**Changes**
`b64decode(base64_data)` => `b64decode(base64_data, validate=True)`
From the `base64` documentation:
>     If validate is False (the default), characters that are neither in the
>     normal base-64 alphabet nor the alternative alphabet are discarded prior
>     to the padding check.  If validate is True, these non-alphabet characters
>     in the input result in a binascii.Error. 
So, if the `inhoud` contained a single `>` character, this was removed (the content became empty) and this caused an error.

Issue 608 upload binary file gives 500

---

src/openzaak/utils/templates/admin/edit_inline/tabular_add_and_edit.html

Fixes #587 
**Changes**
Added the `unlocalize` filter to the template. Now if the PK is larger than 1000 no additional dot appears.

[#587] The PK used in the add_url is now unlocalised

---

src/openzaak/components/catalogi/api/serializers/eigenschap.py
src/openzaak/components/catalogi/models/eigenschap.py
src/openzaak/components/catalogi/tests/admin/test_eigenschap_admin.py
src/openzaak/components/catalogi/tests/test_eigenschap.py

Fixes #685 
**Changes**
During validation of the `lengte` a dot was expected instead of a comma. The replacement of the comma for validation by `Decimal` was added.

Issue 685 eigenschap specificatie validatie inconsistent

---

src/openzaak/components/documenten/api/renderers.py
src/openzaak/components/documenten/tests/test_enkelvoudiginformatieobject.py
src/openzaak/components/documenten/tests/test_enkelvoudiginformatieobject_cmis.py

Fixes #584 
**Changes**
Added a check for when strings are passed to the `BinaryFileRenderer`
In the case where there is an error response and the renderer is `BinaryFileRenderer`, the response content is a string rather than binary data. If a renderer returns a string, the `Response` class attempts to encode it using the specified charset. 
In the `BinaryFileRenderer` the charset is set to `None`, so this caused an error.
Now, inside `BinaryFileRenderer` there is a check for string responses, which are then encoded to UTF-8.

Fixes 584 download non existing EIO causes 500 error

---

src/openzaak/components/documenten/tests/test_cmis_queries.py

A CMIS tag was missing from one of the tests that require Alfresco to be running in order to pass.

Added missing CMIS tag

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/besluiten/tests/test_notifications_kanaal.py
src/openzaak/components/documenten/tests/test_notifications_kanaal.py
src/openzaak/components/zaken/tests/test_auth.py
src/openzaak/components/zaken/tests/test_notifications_kanaal.py
src/openzaak/tests/test_register_kanaal.py

Fixes #738 -- remove the need for vng_api_common.APICredential records

---

CHANGELOG.rst
src/openzaak/components/autorisaties/management/__init__.py
src/openzaak/components/autorisaties/management/commands/__init__.py
src/openzaak/components/autorisaties/management/commands/sync_autorisaties.py
src/openzaak/components/autorisaties/models.py
src/openzaak/components/autorisaties/tests/management/__init__.py
src/openzaak/components/autorisaties/tests/management/test_sync_zaaktype_autorisatie.py
src/openzaak/components/autorisaties/tests/test_autorisatiespec.py
src/openzaak/components/catalogi/__init__.py
src/openzaak/components/catalogi/apps.py
src/openzaak/components/catalogi/signals.py
src/openzaak/components/catalogi/tests/test_zaaktype.py

Fixes #713 
**Changes**
When a `ZaakType` is removed, now there is a receiver for the post delete signal which checks for existing `Autorisaties` and removes them.
A management command was also added to sync existing `Autorisaties` for `ZaakType` instances that have previously been deleted.

Fixes #713 Removing a zaaktype removes the related autorisatie

---

docs/client-development/authentication.rst
docs/client-development/index.rst
docs/client-development/recipes.rst
docs/conf.py
docs/development/index.rst
docs/index.rst
requirements/dev.in
requirements/dev.txt

No issue created for this, sorry!
**Changes**
- Added a documentation section aimed at developers of client applications
- Added basic documentation on the JWT setup
- Added two recipes in Python and Javascript
- creating a zaak, document and relating them
- retrieving the documents related to a zaak in a performant way

Start documentation for client-developers

---

docs/installation/config/cmis.rst
src/openzaak/components/documenten/query/cmis.py
src/openzaak/components/documenten/tests/models/test_human_readable_identification_cmis.py
src/openzaak/components/documenten/tests/test_enkelvoudiginformatieobject.py
src/openzaak/components/documenten/tests/test_enkelvoudiginformatieobject_cmis.py

Fixes #762
**Changes**
More performant CMIS operation by using differently generated Document.identificatie

More performant CMIS operation by using differently generated Document.identificatie

---

docs/installation/config/cmis.rst

Added documentation to explain how to configure the Services and Applicaties required to let the CMIS-adapter retrieve zaken, zaaktypes and besluiten.
I also added the information for the Documenten API, but I am not 100% certain if this is needed.

Documentation for CMIS services config

---

src/openzaak/components/besluiten/api/serializers.py
src/openzaak/components/zaken/api/serializers/zaken.py
src/openzaak/components/zaken/tests/test_zaakinformatieobjecten_cmis.py
src/openzaak/utils/tests.py

Fixes #778 
**Changes**
When CMIS is enabled, the `ZaakInformatieObjectSerializer` and `BesluitInformatieObjectSerializer` method `create()` returns after creating a new object in the same way as for local `ZaakInformatieObject` and `BesluitInformatieObject`.

Fixing duplicate ObjectInformatieObject creation with CMIS

---

src/openzaak/conf/dev.py

**Changes**
When Open Zaak is in debug mode, the logging of the CMIS-adapter is shown in the console by default.

Making debugging of CMIS-adapter easier

---

src/openzaak/components/documenten/query/cmis.py
src/openzaak/components/documenten/tests/test_cmis_queries.py

Fixes #782 
**Changes**
Before, when filtering a `CMISQuerySet`, the `_cmis_query` of the original queryset was updated.
Now, the `_cmis_query` property of the clone of the original queryset is updated.

Changed ordering of cloning/filtering CMISQuerySet

---

.github/workflows/ci.yml
bin/postman_tests.sh
docker-compose.travis.yml
mocks.conf

…nginx container
Fixes #790
**Changes**
* Replaced the mock postman requests with local "endpoints" using static nginx configuration.
* Fix package installation on Github runners for libgdal
Checklist based on https://github.com/VNG-Realisatie/gemma-postman-tests/blob/master/ZGW_mocks.json

Fixes #790 -- Mock HTTP 200, 204 and 404 responses with nginx container

---

src/openzaak/config/templates/admin/config_detail.html

Links that open in a new tab/window without link type `noopener`
or `noreferrer` specified are vulnerable to DOM mutation via
`window.opener`.
Fixes an issue from the _Code scanning alerts_.

Fix potentially unsafe external link

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/documenten/api/serializers.py
src/openzaak/components/documenten/api/validators.py
src/openzaak/components/documenten/management/__init__.py
src/openzaak/components/documenten/management/commands/__init__.py
src/openzaak/components/documenten/management/commands/detect_duplicate_eio.py
src/openzaak/components/documenten/models.py
src/openzaak/components/documenten/query/cmis.py
src/openzaak/components/documenten/tests/test_enkelvoudiginformatieobject.py
src/openzaak/components/documenten/tests/test_enkelvoudiginformatieobject_cmis.py

Fixes #768 
**Changes**
Previously, documents with the same `identificatie` and `bronorganisatie` could be created through the API. There was no unique-together constraint in the database or validator in the document serializer.
A unique-together constraint only on `identificatie` and `bronorganisatie` cannot be added at the database level, because there *can* be multiple documents with same `identificatie` and `bronorganisatie` but different `versie`.
So, for now I only added a `UniekeIdentificatieValidator` [validator](https://github.com/VNG-Realisatie/vng-api-common/blob/master/vng_api_common/validators.py#L301) which checks for the uniqueness of the identificatie within an organisation. I added this validator *only* to the `EnkelvoudigInformatieObjectSerializer` and not to the …

Dont create documents with same identificatie and bronorganisatie

---

src/openzaak/components/documenten/api/serializers.py
src/openzaak/components/documenten/query/cmis.py
src/openzaak/components/documenten/tests/test_gebruiksrechten_cmis.py
src/openzaak/components/documenten/tests/test_objectinformatieobject_cmis.py

Fixes #791 
**Problem description**
After OIOs have been retrieved, they are serialized. The fields `informatieobject` and `zaak` need to be turned into URLs.
For the `informatieobject` field, this is done by passing the canonical object to the `get_url()` function of `EnkelvoudigInformatieObjectHyperlinkedRelatedField`.
```python
def get_url(self, obj, view_name, request, format):
if settings.CMIS_ENABLED:
if isinstance(self.parent.instance, Gebruiksrechten) or isinstance(
self.parent.instance, ObjectInformatieObject
):
eio_latest_version = self.parent.instance.get_informatieobject()
elif isinstance(self.parent.instance, InformatieobjectRelatedQuerySet):
eio_latest_version = self.parent.instance.get().get_informatieobject()    # <====== PROBLEM
else:
eio_latest_version = …
```

Fixes #791 Retrieve OIOs with CMIS enabled

---

src/openzaak/components/besluiten/api/serializers.py
src/openzaak/components/catalogi/api/serializers/besluittype.py
src/openzaak/components/catalogi/api/serializers/eigenschap.py
src/openzaak/components/catalogi/api/serializers/informatieobjecttype.py
src/openzaak/components/catalogi/api/serializers/relatieklassen.py
src/openzaak/components/catalogi/api/serializers/resultaattype.py
src/openzaak/components/zaken/api/serializers/zaken.py
src/openzaak/components/zaken/models/zaken.py
src/openzaak/components/zaken/tests/test_zaakinformatieobjecten.py
src/openzaak/components/zaken/tests/test_zaakinformatieobjecten_cmis.py
src/openzaak/utils/validators.py

**Changes**
When debugging open-zaak with the CMIS-adapter, we noticed that during handling of exceptions many queries to the DMS were performed. These came from the representations of `ZaakInformatieObject` and the `UniqueTogetherValidator` in the `ZaakInformatieObjectSerializer` (https://github.com/open-zaak/open-zaak/blob/master/src/openzaak/components/zaken/api/serializers/zaken.py#L540).
So, the following changes were made:
1. The `__repr__` method of the `UniqueTogetherValidator` (from django rest framework) was over written. Now it no longer iterates over its queryset and creats a representation for each item in the queryset. Now it only prints the name of the validator and on which fields the unique-together constraint applies. All the models in openzaak which used the …

Modified ZaakInformatieObject and UniqueTogetherValidator representations

---

docs/client-development/recipes.rst

The Service needs to be used to build the client, rather than
the service being the client itself.
Fixes #815
**Changes**
* Updated all service `.get()` alls to also build the client from the service

Fixes #815 -- fix example recipes using zgw-consumers

---

src/openzaak/components/besluiten/tests/test_besluitinformatieobjecten_cmis.py
src/openzaak/components/documenten/models.py
src/openzaak/components/documenten/tests/test_audittrails.py
src/openzaak/components/documenten/tests/test_audittrails_cmis.py
src/openzaak/components/documenten/tests/test_eio_delete_cascade_cmis.py
src/openzaak/components/documenten/tests/test_enkelvoudiginformatieobject_cmis.py
src/openzaak/components/zaken/tests/test_zaakinformatieobjecten_cmis.py

Fixes #822 
**Changes**
Before, the reference to the documents were checked by filtering on canonical objects. This however doesn't work with CMIS is enabled and the filtering should be done on the document URLs.

Fixes #822 Cant delete documents unrelated to Zaak

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/besluiten/api/serializers.py
src/openzaak/components/besluiten/tests/test_audittrails.py
src/openzaak/components/besluiten/tests/test_besluit_read.py
src/openzaak/components/zaken/api/viewsets.py
src/openzaak/components/zaken/tests/test_zaak_delete.py
src/openzaak/components/zaken/tests/test_zaakinformatieobjecten.py
src/openzaak/utils/serializers.py
src/openzaak/utils/validators.py

Relates to #819
While testing the remote DRC integration with the DRC reference implementation service, it turns out that there were more defects in Open Zaak that prevented this from working correctly.
All the issues were uncovered by the test suite on api-test.nl, in combination with the `vngr/gemma-drc:1.0.1.post0` reference implementation of a DRC.
**Changes**
* added regression test for (partial) update validation of `ZaakInformatieObject` where the remote Documents API url does not change
* fixed validation bug where instance comparison happened rather than URL comparison if CMIS is not enabled
* added regression test and fix for remote OIO `DELETE` call on cascading zaak-destroy operations
* added regression test and fix for `Besluit.zaak` being output as `null` in the API, which …

Fix Open Zaak handling of remote DRCs

---

docs/conf.py
src/openzaak/management/commands/send_test_notification.py

Fixes #667
**Changes**
* When using the `send_test_notification` command, a `CommandError` is now raised if Notifications are not configured properly

:goal_net: Raise proper error if NRC is not configured when testing notifs send

---

deployment/single-server/README.md

Fixes #717
Instead of providing a short summary with instructions, the README
now refers to the documentation on readthedocs. The target users
of the code itself is now mentioned clearly.

Fixes #717 -- rewrite single-server README

---

src/openzaak/conf/includes/base.py

Fixes #807
**Changes**
* Increase `DATA_UPLOAD_MAX_NUMBER_FIELDS` to 10000 to allow large auth operations (for many zaaktypen for example)

:wrench: Increase DATA_UPLOAD_MAX_NUMBER_FIELDS for large auth operations

---

docs/installation/post_install.rst

Fixes #721
**Changes**
* Removed the `raven test` command from the post install docs, as it doesn't exist

:memo: Remove raven command from post install docs

---

src/openzaak/components/documenten/models.py
src/openzaak/components/documenten/query/cmis.py
src/openzaak/components/documenten/tests/test_gebruiksrechten.py
src/openzaak/components/documenten/tests/test_gebruiksrechten_cmis.py

Fixes #811 
**Changes**
The `save()` method of Gebruiksrechten now actually calls functions in the CMIS adapter to save the modification of the gebruiksrechten. 
The PR is marked as WIP only because the `drc_cmis` requirement is pinned to a commit rather than a released version.

Gebruiksrechten get updated when CMIS is enabled

---

src/openzaak/templates/index.html
src/openzaak/templates/master.html

Fixes #753
**Changes**
* linked to gemma-zaken github pages in footer
* changed zaakgerichtwerken.vng.cloud link to the redirect target
* for each component, include a block/link to the runtime behaviour documentation

improve documentation links

---

docs/introduction/open-source/public_code.md

Fixes #864
**Changes**
Security email and instructions have been added.
The v.0.2.1 template added a new requirement on no mandatory transfer of
copyright, which OpenZaak already meets.

Update Standard for Public Code checklist

---

docs/introduction/open-source/dependencies.rst
docs/introduction/open-source/index.rst
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Fixes #681
* Bumped a couple of dependencies that have since reached a 1.0 version or higher
* Documented the < 1.0 dependencies with the mitigations for the risks

Fixes #681 -- Documenting the < 1.0.0 dependency versions

---

src/openzaak/components/catalogi/api/serializers/zaaktype.py
src/openzaak/components/catalogi/api/validators.py
src/openzaak/components/catalogi/tests/test_zaaktype.py

Fixes #850 
**Changes**
This adds a new validation check in the serializer to prevent a 500 error.  
We were doing this check on the `save` method of the model here https://github.com/open-zaak/open-zaak/blob/master/src/openzaak/components/catalogi/models/zaaktype.py#L305-L307 however if this exception is raised then the API responds with a 500 error while we want a 400 error to be returned.
By adding the validator the API will now return a user friendly 400 error.

Add validator in serializer to prevent 500 error

---

src/openzaak/components/zaken/api/filters.py
src/openzaak/components/zaken/tests/test_zaakinformatieobjecten.py
src/openzaak/components/zaken/tests/test_zaakinformatieobjecten_cmis.py

Fixes #820
**Cause of the problem**
The `ZaakInformatieObject` have a filterset class `ZaakInformatieObjectFilter` which specifies how to filter on the FKorURLField `informatieobject`. 
When the dictionary of filters is generated (here: https://github.com/maykinmedia/django-loose-fk/blob/develop/django_loose_fk/filters.py#L58) the document is considered 'local' even though it is in the DMS. Because of this, the ZIOs are filtered using the canonical object, but this doesn't work if CMIS is enabled, so the wrong ZIOs are returned.
**Changes**
I overwrote the `filter()` method of the `ZaakInformatieObjectFilter` class to take into account the CMIS case.

Fixes #820 - Filtering ZIOs on informatieobject with CMIS enabled

---

docs/introduction/open-source/public_code.md

See https://github.com/open-zaak/open-zaak/issues/679
The 'Zaakgericht Werken in het Gemeentelijk Gegevenslandschap' seems
to meet the requirements of 'Open Standards Requirement for Software'.
https://www.gemmaonline.nl/images/gemmaonline/f/f6/20190620_-_Zaakgericht_werken_in_het_Gemeentelijk_Gegevenslandschap_v101.pdf
https://opensource.org/osr
Fixes #
**Changes**

Stadards meet OSR requirements (issue #679)

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/utils/tests.py

**Changes**
The `main_repo_id` is configured before the tests start. 
With the improved handling of `main_repo_id` in the CMIS adapter, this speeds up running tests with the WEBSERVICE binding.
(This PR is a draft because it requires https://github.com/open-zaak/cmis-adapter/pull/43 to be released)

Improve CMIS tests performance

---

src/openzaak/wsgi.py

**Changes**
In the past we were using New Relic actively and had this commented out in the wsgi.py file to easily enable APM monitoring.
However this was long ago and we now internally use self-hosted elastic-apm for most production systems. Enabling this for open-zaak could be interesting, but as I'm cleaning up newrelic from older projects I've done this too for open-zaak.

Removing disabled newrelic APM monitoring

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/catalogi/api/filters.py
src/openzaak/components/catalogi/tests/test_filters.py

Fixes #870 
**Changes**
By changing the CharFilter to a ChoiceFilter the user will receive a 400 error response and the following data back rather than a 500 error
```
{
"type": "http://localhost:8000/ref/fouten/ValidationError/",
"code": "invalid",
"title": "Invalid input.",
"status": 400,
"detail": "",
"instance": "urn:uuid:48c051dc-0064-4529-b899-e3b0bd83367b",
"invalidParams": [
{
"name": "status",
"code": "invalid_choice",
"reason": "Selecteer een geldige keuze. %(value)s is geen beschikbare keuze."
}
]
}
```
The only thing I don't like is that `%(value)s` is returned instead of the value they passed in.  This happens because `django-filter`  here https://github.com/carltongibson/django-filter/blob/2.0.0/django_filters/utils.py#L320 uses `e.message` without passing in  the proper …

Change CharFilter to a ChoiceFilter 

---

src/openzaak/components/catalogi/api/viewsets/zaaktype.py
src/openzaak/components/catalogi/tests/test_zaaktype.py

Fixes #851 
**Changes**
When doing a `PUT` on the `zaaktypen` endpoint we want to delete `ZaakTypenRelatie` that were previously created so that they can be recreated in this `PUT` request.

Prevent exception when doing PUT and ZaakTypenRelatie already exists

---

src/openzaak/management/commands/setup_configuration.py

**Changes**
This configures the script to update the Notificaties API Service so it's setup correctly by the script.  It updates the `auth_type` of the service because the check the endpoint `view-config` does assumes a certain `auth_type`  and creates a `client_id` and `secret` that can then be used to configure your Open Notificaties instance.
The client_id and secret will be written to the console when running the script. Eg.
```bash
Initial configuration for Open Zaak was setup successfully
Notificaties API Service configured with client_id open-zaak-1O4OzrcxfrFk and secret cnlFSqx5B9vI.  Use this to configure your Open Notifications instance.
```
I tested this by going to the `view-config` endpoint on my localhost.
Screenshot

Configure Notificaties API service in setup_configuration script

---

src/openzaak/components/autorisaties/admin.py
src/openzaak/components/autorisaties/admin_filters.py
src/openzaak/components/autorisaties/api/viewsets.py
src/openzaak/components/autorisaties/tests/test_authorizations_api.py
src/openzaak/components/autorisaties/tests/test_notifications_send.py
src/openzaak/components/catalogi/signals.py

Fixes #835
**Changes**
* Prevent invalid/not-ready applications from showing up in the API (missing authorizations / superuser flag, or having both)
* Display readiness in admin list + hints on how to resolve un-readiness
* Added filter in admin so that invalid apps can quickly be retrieved
Preview:

Fix invalid applications showing up in the Autorisaties API

---

src/openzaak/components/documenten/query/cmis.py
src/openzaak/components/documenten/tests/test_eio_file_cmis.py

Fixes #881 
The dependency on the cmis-adapter needs to be updated when https://github.com/open-zaak/cmis-adapter/pull/46 is released.

Fixes #881 - Create document without identificatie

---

SECURITY.rst

Part of issue #871, Service providers should be on the [OpenZaak Release Early Notice List](https://odoo.publiccode.net/survey/start/086e0627-8bc0-4b65-8aa9-f6872aba89d0).

Document advice to service providers

---

src/openzaak/components/documenten/query/cmis.py
src/openzaak/components/documenten/tests/test_utils_cmis.py
src/openzaak/components/zaken/tests/test_zaakinformatieobjecten_cmis.py

Fixes #925 
Fixes https://github.com/open-zaak/cmis-adapter/issues/51
**Changes**
Instead of passing the CMIS-adapter the zaak and zaaktype data coming from `model_to_dict`, the required properties are extracted manually and returned in a dictionary.

Fixes #925 - Missing metadata in zaak and zaaktype

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

This includes updated support for Azure AD.
**Changes**
* Updated django-auth-adfs from 1.3.x to 1.6.x
* Updated django-auth-adfs-db from 0.2.0 to 0.3.0

Bump django-auth-adfs(-db) to latest versions

---

docs/installation/config/env_config.md
src/openzaak/conf/includes/base.py
src/openzaak/tests/test_x_forwarded_host.py

Fixes #916
**Changes**
* Added opt-in to get the request host from the `X-Forwarded-Host` header

Support X-Forwarded-Host header

---

docs/installation/config/openzaak_config.rst

Fixes #947
Fixed some small errors in the documentation.
**Changes**
Added missing configuration steps describing how Open Notificaties can receive notifications of changes in the authorisation component of Open Zaak.

Improved Open Zaak configuration documentation

---

src/openzaak/components/catalogi/admin/forms.py
src/openzaak/components/catalogi/tests/admin/test_import_export_zaaktype.py

Fixes #964
**Changes**
Only compare fields that are submitted in the POST request - published zaaktypen are read-only so the fields are absent.

Fix exporting published zaaktypen

---

src/openzaak/components/documenten/api/validators.py
src/openzaak/components/documenten/api/viewsets.py
src/openzaak/components/documenten/tests/factories.py
src/openzaak/components/documenten/tests/test_objectinformatieobject.py
src/openzaak/components/documenten/tests/test_objectinformatieobject_cmis.py

These came up during testing by Contezza, many thanks for that!
**Changes**
* the `RemoveRelationValidator` now emits the correct error code `remote-relation-exists` instead of `inconsistent-relation`
* the `RemoveRelationValidator` now validates external URLs as well instead of letting those through (when deleting ObjectInformatieObject)

Fix alignment with DRC reference implementation (1.0.x)

---

CHANGELOG.rst
Dockerfile

to ensure that containers can be run as non-root users

:whale: Drop superuser priviliges in Dockerfile

---

src/openzaak/components/besluiten/models.py
src/openzaak/components/besluiten/tests/admin/test_besluit_admin.py
src/openzaak/components/besluiten/tests/test_besluit_create.py
src/openzaak/components/zaken/models/zaken.py
src/openzaak/components/zaken/tests/admin/test_zaak_admin.py
src/openzaak/components/zaken/tests/test_create.py

Fixes #890
**Changes**
* Added API tests to make the behaviour explicit
* Added admin regression tests
* Removed alphanumeric validators from `Zaak.identificatie` and `Besluit.identificatie`
Replaces #944

Allow all characters in (Besluit|Zaak).identificatie (admin)

---

src/openzaak/components/autorisaties/admin.py
src/openzaak/components/autorisaties/tests/admin/test_autorisaties_admin.py
src/openzaak/components/autorisaties/tests/management/test_sync_zaaktype_autorisatie.py
src/openzaak/components/autorisaties/tests/test_autorisatiespec.py
src/openzaak/conf/includes/base.py

Fixes #860
The 'manage authorizations' view presents a condensed, aggregated view
of the different authorizations for a given API application.
The regular admin interface displayed all authorizations as inline with
the application, but because of the amount of possible combinations
(different zaaktypen, documenttypen, besluittypen... and permissions),
this inline can quite easily exceed 10.000 records.
Once that number is exceeded, Django blocks the request because
`DATA_UPLOAD_MAX_NUMBER_FIELDS` is exceeded. Removing the inlines
fixes this.
**Changes**
* `Applicatie.autorisaties` inline removed with relevant tests
* `DATA_UPLOAD_MAX_NUMBER_FIELDS` reset to original value of 1000 (setting removed, using the Django default again)

Fixes #860 -- remove autorisatie-inlines for applicaties

---

src/openzaak/components/besluiten/tests/test_besluit_create.py
src/openzaak/components/besluiten/tests/test_besluitinformatieobjecten.py
src/openzaak/components/besluiten/tests/test_filters.py
src/openzaak/components/documenten/tests/test_objectinformatieobject.py
src/openzaak/components/zaken/tests/test_create_melding_rol.py
src/openzaak/components/zaken/tests/test_statussen.py
src/openzaak/components/zaken/tests/test_zaak_zoek.py
src/openzaak/components/zaken/tests/test_zaakinformatieobjecten.py
src/openzaak/components/zaken/tests/test_zaakobject_filter.py

My `.env` locally often breaks tests when running tests locally, while they pass in CI -> test isolation/pinning is not good enough.

Improving test isolation

---

src/openzaak/components/zaken/api/serializers/zaken.py
src/openzaak/components/zaken/tests/test_validation.py

Fixes #960
**Changes**
* Added `UniqueTogetherValidator` to catch unique constraint violations before they hit the DB

Validate unique constraint zaakstatus

---

src/openzaak/tests/test_jwt_auth.py

Fixes #936
**Changes**
* Added regression test
* Fix applied in vng-api-common: https://github.com/VNG-Realisatie/vng-api-common/commit/9495766b3355603688cdb05378d8fd36afe743af
* Bumped to newer vng-api-common

Fix crash on null user id in JWT

---

src/openzaak/notifications/tests/utils.py

HTTP 4xx and HTTP 5xx can be expected at times. If the exception
is caught, we should not be seeing a traceback in CI for this.

:mute: Do not output logging for caught API errors

---

src/openzaak/fixtures/default_admin_index.json

Fixes #830
**Changes**
Added links to:
* Docs website
* Mailing list
* Security early-notice
* Website
* Slack server Common Ground
* Github
* VNG standard + documentation

Fixes #830 -- add admin index tab with useful links

---

.readthedocs.yml
requirements/rtd.txt

RTD also runs 'pip install -U setuptools' which breaks stuff.

Pin setuptools for RTD builds

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Some extra functionality and bugfixes for the OpenID Connect integration, mentioned in the changelog: https://github.com/maykinmedia/mozilla-django-oidc-db/blob/master/CHANGELOG.rst

:arrow_up: Bump mozilla-django-oidc-db to 0.7.1

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

**Changes**
* Bumped to Django 2.2.25
* Bumped to sqlparse 0.4.2
* Bump dev dependency Babel to 2.9.1

:arrow_up: Bump Django, babel and sqlparse

---

src/openzaak/components/zaken/api/validators.py

I think that the comma in the dictionary was meant to be a colon.

Problem with error formatting

---

docs/introduction/open-source/public_code.md

Fixes #1087
**Changes**
Updated `docs/introduction/open-source/public_code.md` to match the [current v0.2.2 template](https://github.com/publiccodenet/about/blob/develop/activities/codebase-auditing/review-template.md)
Co-authored-by: Jan Ainali <ainali.jan@gmail.com>

Update the assessment of the codebase to the Standard for Public Code v0.2.2

---

CONTRIBUTING.md
GOVERNANCE.md
docs/development/roadmap.rst

Changed product steering team to core group, and removed specifics about their process.
Fixes #781

Change product steering team to core group

---

src/openzaak/components/besluiten/api/viewsets.py
src/openzaak/components/besluiten/tests/test_audittrails.py
src/openzaak/components/documenten/api/viewsets.py
src/openzaak/components/documenten/tests/test_audittrails.py
src/openzaak/components/zaken/api/permissions.py
src/openzaak/components/zaken/api/viewsets.py
src/openzaak/components/zaken/tests/test_audittrails.py
src/openzaak/components/zaken/tests/test_zaakbesluiten.py
src/openzaak/components/zaken/tests/test_zaakeigenschap.py

Fixes: https://github.com/open-zaak/security-issues/issues/3
**Changes**
* Use the proper permission_classes for audittrail viewsets, to enable checking for expired JWTs
* Check JWT expiry for nested Zaak resources

:lock: Check JWT expiry for audittrails and nested Zaak resources

---

src/openzaak/components/autorisaties/tests/test_notifications_send.py
src/openzaak/components/besluiten/tests/test_besluitinformatieobjecten.py
src/openzaak/components/besluiten/tests/test_notifications_send.py
src/openzaak/components/catalogi/tests/test_notifications_send.py
src/openzaak/components/documenten/tests/test_enkelvoudiginformatieobject.py
src/openzaak/components/documenten/tests/test_notifications_send.py
src/openzaak/components/documenten/tests/test_validation.py
src/openzaak/components/zaken/tests/test_notifications_send.py
src/openzaak/components/zaken/tests/test_relevantezaakrelatie.py
src/openzaak/components/zaken/tests/test_resultaten.py
src/openzaak/components/zaken/tests/test_rol.py
src/openzaak/components/zaken/tests/test_statussen.py
src/openzaak/components/zaken/tests/test_validation.py
src/openzaak/components/zaken/tests/test_zaakeigenschap.py
src/openzaak/components/zaken/tests/test_zaakinformatieobjecten.py
src/openzaak/components/zaken/tests/test_zaken.py

This should remove real HTTP calls from the test suite and eventually make
it possible to run the tests offline.
* removes real calls to example.com
* remove real calls to notifications API

Tests: running offline, first pass

---

.dockerignore
.github/workflows/ci.yml
Dockerfile

Related to #1097 -- the base images have been updated from Debian oldoldstable to
stable. Django support for libgdal 3.x has been confirmed in later
releases without code modifications.
Additionally, some dockerfile lines have been moved around for better cache
utilization.

Update base images to bullseye-slim from stretch

---

docs/introduction/open-source/public_code.md

Fixes #1117
**Changes**
The use of review templates and linking to issues demonstrates that decisions are documented in commit messages, and this is supported by the text of the `CONTRIBUTING.md`

Standard for Public Code assessment of "Maintain version control"

---

src/openzaak/sass/admin/_admin_theme.scss
src/openzaak/sass/admin/_vendor.scss
src/openzaak/sass/admin/admin_overrides.scss
src/openzaak/templates/admin/base.html
src/openzaak/templates/admin/object_history.html

Fixes #1122
**Changes**
* Included custom overrides after bootstrap stylesheets to leverage the
cascading nature of CSS. This ensures our own values for CSS vars are
used instead of bootstrap's reboot.
* Copied django admin/base.html template and added an extra block for
modals. The alignment of django-admin z-indices combined with where
bootstrap injects the modal backdrop requires this change to break
everything modal-related outside of the nested document structure.

Fix styles broken by bootstrap

---

docs/installation/config/env_config.md
src/openzaak/conf/includes/base.py
src/openzaak/conf/production.py

Fixes #1145
**Changes**
By default, we now only log WARNING log levels, but this can be overridden through envvars. Before we had varying degrees of `DEBUG` output cluttering the emitted logs.

Make log level configurable

---

bin/postman_tests.sh

Issue: #1109 
**Changes**
* Retrieve the ZGW postman tests directly from github, instead of using ATP
Manual run of CI to check if it succeeds: https://github.com/open-zaak/open-zaak/actions/runs/2219210454

:construction_worker: Pull ZGW test suite from github in CI

---

docs/introduction/index.rst
docs/introduction/upstream-api-parity.rst

Sorry for the delays, this has been pending for a while.
This pull request drafts the policy of the Technical Steering Group with regard to API version alignment to the upstream standard maintained by VNG. Last technical steering group was held because of [this email thread](https://lists.publiccode.net/hyperkitty/hyperkitty/list/openzaak-discuss@lists.publiccode.net/thread/A4B3UH4Y2IWE7XAIDO4YF2QJDKJWINSK/) to discuss "Adding non-standard API features into Open Zaak". I've tried to document the concerns, motivation and policy as we discussed during the meeting.
Feel free to make remarks and suggestions, I've mostly focused on getting an initial draft out that we can shoot at :smile:

Draft API parity policy

---

src/openzaak/components/catalogi/api/serializers/zaaktype.py
src/openzaak/components/catalogi/api/validators.py
src/openzaak/components/catalogi/tests/test_zaaktype.py

Fixes #983
**Changes**
Updated validator to not check for related published documenttypes (and modified the test), as this falls under the exception for ZTC-10 and ZTC-11 rules.
I've also checked the behaviour for creating those relations and think we cover it correctly with the tests/validators.
I am however curious if this bug is also present in the VNG test suite, so I'm expecting potential build failures there. If that's the case, we need to get that test-suite fixed as well.

Allow updating a zaaktype with relations to published documenttypes

---

src/openzaak/components/catalogi/admin/besluittype.py
src/openzaak/components/catalogi/admin/filters.py
src/openzaak/components/catalogi/admin/informatieobjecttype.py
src/openzaak/components/catalogi/admin/zaaktypen.py
src/openzaak/components/catalogi/tests/admin/test_zaaktype_admin.py

Fixes #510
**Changes**
* Added filter option on concept yes/no
* Implemented a filter on validity, partitioning the data in "valid in the past", "valid now", "valid in the future"
* Display the begin/einde geldigheid in the admin list

Implement zaaktype list / filtering in the admin

---

src/openzaak/components/catalogi/api/validators.py
src/openzaak/components/catalogi/tests/test_zaaktype.py
src/openzaak/utils/serializers.py

Fixes #981
**Changes**
* Added test to check the value can be set to null
* Added test to check that changes introducing overlap are still blocked
* Made validation error field context-dependent (if we're patching just the field eindeGeldigheid -> then errors are attached there)
* Fixed bug that prevented patches setting eindeGeldigheid to `None` from succeeding
TODO: backport to reference implementation (probably)

Allow null eindegeldigheid in catalogi api

---

src/openzaak/components/catalogi/admin/forms.py
src/openzaak/components/catalogi/admin/zaaktypen.py
src/openzaak/components/catalogi/tests/admin/test_import_export_zaaktype.py
src/openzaak/components/catalogi/tests/admin/test_published_readonly.py
src/openzaak/components/catalogi/tests/admin/test_resultaattype_admin.py
src/openzaak/components/catalogi/tests/admin/test_zaaktype_admin.py
src/openzaak/components/catalogi/tests/models/test_resultaattype_validation.py
src/openzaak/selectielijst/tests/mixins.py

Fixes #970
**Changes**
* When editing the zaaktype procestype (selectielijst), this is now checked for integrity against related resultaattypen
* Because you cannot modify resultaattype with a selectielijstklasse that doesn't belong to the zaaktype.procestype, this cross-validation blocked edits completely. To mitigate this, a reset option is added which resets all selectielijst-related configuration in the entire zaaktype (including resultaattypen)
* Fixed tests and cleaned up some divergent patterns into single mixin

Validate selectielijst resultaattypen in zaaktype admin + add reset option

---

src/openzaak/components/zaken/api/serializers/zaken.py
src/openzaak/components/zaken/api/validators.py
src/openzaak/components/zaken/tests/test_validation.py
src/openzaak/components/zaken/tests/utils.py

Fixes #992
**Changes**
* Added validator to check that zaak.zaaktype is in zaak.hoofdzaak.zaaktype.deelzaaktypen
* Added tests for both local/remote zaaktypen
* Worked around some broken test isolation because of process-level caches

Validate deelzaak zaaktype with hoofdzaak.zaaktype.deelzaaktypen

---

src/openzaak/components/zaken/api/viewsets.py
src/openzaak/components/zaken/tests/test_filters.py

Fixes #1023
**Changes**
Modified viewset queryset to only emit distinct results.
I looked into specifying the `distinct=True` option to the filterset field, but since this is all going through regular introspection, this solution is much more explicit and easier to understand with the same end-result.

Fix duplicate results returned in zaak list endpoint

---

.babelrc
package-lock.json
package.json
src/openzaak/components/catalogi/admin/forms.py
src/openzaak/components/catalogi/admin/resultaattype.py
src/openzaak/components/catalogi/api/admin/__init__.py
src/openzaak/components/catalogi/api/admin/urls.py
src/openzaak/components/catalogi/api/admin/views.py
src/openzaak/components/catalogi/tests/admin/api/__init__.py
src/openzaak/components/catalogi/tests/admin/api/test_selectielijst.py
src/openzaak/components/catalogi/tests/admin/test_resultaattype_admin.py
src/openzaak/components/catalogi/tests/models/test_resultaattype_validation.py
src/openzaak/js/components/admin/index.js
src/openzaak/js/components/admin/resultaattypen/index.js
src/openzaak/js/components/admin/resultaattypen/selectielijst.js
src/openzaak/js/components/admin/zaaktypen/index.js
src/openzaak/js/components/admin/zaaktypen/selectielijst.js
src/openzaak/templates/admin/catalogi/change_list.html
src/openzaak/urls.py

~~Depends on #1161~~
Fixes #1030
**Changes**
* The list of possible selectielijstklassen is now only shown if the zaaktype has a selectielijst procestype specified. If it hasn't (or the zaaktype is not known yet), then the field is disabled and an empty value can be stored
* Publishing a zaaktype now validates that all resultaattypen have a selectielijstklasse specified. Combined with the previous change, this allows a more iterative configuration without losing any work.
* The zaaktype in the "admin voodoo" is now also grabbed from the POST data instead of only GET parameter
* The possible options for selectielijstklasse are now refreshed/rendered based on the chosen zaaktype. Changing the zaaktype causes the relevant list to be loaded
* Refresh list of procestypen in dropdown when the …

Improve handling of selectielijst in the catalogi admin

---

src/openzaak/components/autorisaties/tests/admin/test_autorisaties_admin.py
src/openzaak/components/catalogi/signals.py

Fixes #1081
This test could not reproduce the issue, the behaviour is probably
already fixed via #713 and 9e799673e. However, we found an edge case
related to #1080 where the entire application would be deleted
even if there are still blueprints attached to it.

Added test for cascading autorisatie-delete on IOType delete

---

src/openzaak/components/catalogi/admin/forms.py
src/openzaak/components/catalogi/admin/mixins.py
src/openzaak/components/catalogi/admin/zaaktypen.py
src/openzaak/components/catalogi/tests/admin/test_admin_publish.py
src/openzaak/components/catalogi/tests/admin/test_zaaktype_admin.py

Fixes #1085
**Changes**
* Extra validation runs on zaaktype publish
* Check that a roltype is defined
* Check that a resultaattype is defined
* Check that at least two statustypen are defined
* Also run form-validation on bulk publish and convert the errors in admin messages

Extend admin validations on zaaktype publish

---

.dockerignore

This excludes tests, cached bytecode and test assets from ending up in the final container image.
This code is never meant to be run or used in production scenario's,
so we remove dead weight. A nice benefit is that the container image
should be a bit smaller in the end.

:whale: Reduce docker build context and image size

---

docs/conf.py
docs/installation/docker_compose.rst
docs/installation/index.rst
docs/installation/kubernetes.rst
docs/installation/single_server.rst
docs/installation/updating.rst

Fixes #1001
**Changes**
* broke out deploy into docker-compose, Kubernetes, single-server and
local development
* Within Kubernetes, promoted Helm option as first option, then Ansible
* Reworded bits and pieces here and there
* Updated supported OS-list to reflect the reality

Restructure deployment documentation

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Fixes #1186
**Changes**
Bumped to vng-api-common 1.7.8 which includes "smart" migrations to detect the right course of action.

Bump to patched vng-api-common

---

src/openzaak/components/catalogi/admin/mixins.py
src/openzaak/components/catalogi/models/eigenschap.py
src/openzaak/components/catalogi/models/resultaattype.py
src/openzaak/components/catalogi/models/roltype.py
src/openzaak/components/catalogi/models/statustype.py
src/openzaak/components/catalogi/models/validators.py
src/openzaak/components/catalogi/tests/admin/test_eigenschap_admin.py
src/openzaak/components/catalogi/tests/admin/test_resultaattype_admin.py
src/openzaak/components/catalogi/tests/admin/test_roltype_admin.py
src/openzaak/components/catalogi/tests/admin/test_statustype_admin.py

Fixes #1042 
**Changes**
* Disallow mutating published ZaakTypen via the admin
* Fix change form incorrectly displaying as readonly

:bug: [#1042] Disallow mutating published ZaakTypen via the admin

---

src/openzaak/components/besluiten/tests/test_besluit_create.py
src/openzaak/components/besluiten/tests/test_besluit_with_external_zaak.py
src/openzaak/components/besluiten/tests/test_besluitinformatieobjecten.py
src/openzaak/components/documenten/tests/test_objectinformatieobject.py
src/openzaak/components/zaken/tests/test_relevantezaakrelatie.py
src/openzaak/components/zaken/tests/test_resultaten.py
src/openzaak/components/zaken/tests/test_rol.py
src/openzaak/components/zaken/tests/test_statussen.py
src/openzaak/components/zaken/tests/test_zaak_archive.py
src/openzaak/components/zaken/tests/test_zaakbesluiten.py
src/openzaak/components/zaken/tests/test_zaakeigenschap.py
src/openzaak/components/zaken/tests/test_zaakinformatieobjecten.py
src/openzaak/components/zaken/tests/test_zaken.py

Replace `real_http=True` with proper schema-fetch mocks.
I confirmed the test suite is now running/passing locally with networking disabled :tada:

Remove real_http=True in test mocks

---

src/openzaak/components/besluiten/tests/utils.py
src/openzaak/components/documenten/api/validators.py
src/openzaak/components/documenten/api/viewsets.py
src/openzaak/components/documenten/tests/test_objectinformatieobject.py
src/openzaak/components/documenten/tests/test_objectinformatieobject_cmis.py
src/openzaak/components/zaken/tests/utils.py

Fixes #1227
**Changes**
* Validate if the remote relation exists before creating an ObjectInformatieObject

:bug: [#1227] Validate that remote OIO relation exists

---

src/openzaak/conf/includes/base.py

to fix failing exports for large catalogi
I noticed that this setting was removed in https://github.com/open-zaak/open-zaak/pull/998, but when attempting to export a large catalogus, it raised issues again

:wrench: Set DATA_UPLOAD_MAX_NUMBER_FIELDS to 10000

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Fixes Taiga DH 405
**Changes**
Updating of mozilla-django-oidc-db to 0.11.0 to allow configuration of default permissions in OpenZaak
Replaces PR #1250

Updating mozilla-django-oidc-db to 0.11.0

---

src/openzaak/components/zaken/api/serializers/zaken.py
src/openzaak/components/zaken/api/viewsets.py
src/openzaak/components/zaken/tests/test_zaak_zoek.py
src/openzaak/utils/filters.py

Fixes #1198
**Changes**
* Moved empty search body/parameters validation to view
* Added test for filter backend (search-capable)
* Added regression test for broken ordering
* Fixed looking up ordering parameter in request body

Fix zaak zoek ordering parameter

---

.github/workflows/codeql-analysis.yml

v1 will be deprecated in December, see
https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/

Upgrade CodeQL to v2

---

src/openzaak/components/zaken/models/zaken.py
src/openzaak/components/zaken/tests/models/test_unique_representation.py

I ran into this while migrating data from an existing system to Open Zaak.
If it's longer than 200 chars, then the audittrail record saving fails because the representation is a DB column with 200-char limit.

Ensure Rol unique representation does not exceed 200 characters

---

src/openzaak/components/catalogi/admin/mixins.py
src/openzaak/components/catalogi/tests/admin/test_zaaktype_admin.py
src/openzaak/forms/widgets.py

Fixes #1273 and fixes #1275 and also fixes rendering of empty durations for published zaaktypen in the admin UI

:bug: [#1273/#1275] Fix publishing zaaktypen with durations

---

docs/installation/config/index.rst
docs/installation/config/openzaak_config.rst
docs/installation/config/openzaak_config_cli.rst
docs/installation/reference/cli.rst
src/openzaak/config/bootstrap/__init__.py
src/openzaak/config/bootstrap/datastructures.py
src/openzaak/config/bootstrap/exceptions.py
src/openzaak/config/bootstrap/notifications.py
src/openzaak/config/bootstrap/site.py
src/openzaak/config/bootstrap/typing.py
src/openzaak/config/tests/bootstrap/__init__.py
src/openzaak/config/tests/bootstrap/test_notifications_api_configuration.py
src/openzaak/config/tests/bootstrap/test_notifications_autorisaties_api_configuration.py
src/openzaak/config/tests/bootstrap/test_site_configuration.py
src/openzaak/management/commands/send_test_notification.py
src/openzaak/management/commands/setup_configuration.py
src/openzaak/notifications/tests/test_register_kanaal.py
src/openzaak/tests/management/test_setup_configuration.py

Fixes #669
This completely reworks the `setup_configuration` management command
**Changes**
* No more positional arguments, only options/flags
* Interactive vs. silent mode - in interactive mode, options not provided during the invocation are prompted for
* Keep generation of client IDs/secrets if no value is provided and report back the values that are used eventually
* Refactored the actual setup into `openforms.config.bootstrap`, which can in the future also be used by a frontend UI/wizard (if we'd like that, but now it's easier to test)
* Added self-test capabilities by hitting the endpoints with the configuration + reporting the outcomes
* Restructured documentation for configuration between admin and CLI variant
* Updated documentation here and there to account for changes …

Refactor setup_configuration management command

---

docs/installation/config/env_config.md
src/openzaak/conf/ci.py
src/openzaak/conf/dev.py
src/openzaak/conf/docker.py
src/openzaak/conf/includes/base.py
src/openzaak/conf/production.py
src/openzaak/conf/staging.py

Fixes #1280
* You can now specify the environment at deploy-time
* The environment is now configured in the Sentry SDK and sent along with error reports.

Allow providing the ENVIRONMENT via envvar to Sentry

---

setup.cfg

We get some drops in coverage now because some try: except: calls in tests aren't hit (because they are now passing correctly).
Measuring the coverage of the test code by itself already skews the coverage statistics, we only care about the actual application code.

Don't measure the coverage of tests themselves

---

docs/installation/config/env_config.md
docs/installation/config/openzaak_config.rst
docs/installation/index.rst
docs/installation/reference/fq-urls.rst
src/openzaak/components/autorisaties/tests/admin/test_autorisaties_admin.py
src/openzaak/components/autorisaties/utils.py
src/openzaak/components/catalogi/admin/forms.py
src/openzaak/components/catalogi/admin/zaaktypen.py
src/openzaak/components/catalogi/management/commands/export.py
src/openzaak/components/catalogi/tests/admin/test_zaaktypenrelatie_admin.py
src/openzaak/components/catalogi/tests/management/test_import_export.py
src/openzaak/conf/includes/base.py
src/openzaak/management/commands/setup_configuration.py
src/openzaak/tests/test_rewrite_host.py
src/openzaak/utils/__init__.py
src/openzaak/utils/checks.py
src/openzaak/utils/middleware.py

Fixes #1020
**Changes**
* Rewrite HTTP_HOST at the request level.
* Deprecate `Site.objects.get_current().domain` usage in favour of `OPENZAAK_DOMAIN`
* Use `OPENZAAK_DOMAIN` in `build_absolute_url` if available
* Added system checks to detect bad/ambiguous configurations

add middleware to rewrite the request host

---

fixtures/fixture.json

this used to be http, because the new referentielijsten API implementation returned all urls with http, causing issues when trying to fetch a Service for one of those urls (see https://github.com/open-zaak/open-zaak/pull/1378#issuecomment-1538024216). This is now fixed and no longer needed
https://github.com/open-zaak/open-zaak/issues/1359

:green_heart: Use https for referentielijsten in postman tests

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Fixes #1374 
**Changes**
* Bump commonground-api-common to 1.10.2 to benefit from improved identificatie generation

:arrow_up: [#1374] Bump commonground-api-common to 1.10.2

---

src/openzaak/components/zaken/api/filters.py
src/openzaak/components/zaken/openapi.yaml
src/openzaak/components/zaken/swagger2.0.json
src/openzaak/components/zaken/tests/test_zaken.py

Fixes #1075
This PR was created to replace #1076 PR since the previous PR was made in the fork and can't be rebased 
PR in upstream has been merged: https://github.com/VNG-Realisatie/zaken-api/pull/208
**Changes**
* Added five extra filters for Zaken endpoint:
* rol__betrokkeneIdentificatie__natuurlijkPersoon__anpIdentificatie
* rol__betrokkeneIdentificatie__natuurlijkPersoon__inpA_nummer
* rol__betrokkeneIdentificatie__nietNatuurlijkPersoon__innNnpId
* rol__betrokkeneIdentificatie__nietNatuurlijkPersoon__annIdentificatie
* rol__betrokkeneIdentificatie__vestiging__vestigingsNummer

Gemeente den haag feature/zaken rol identificaties filters

---

docker/nginx/default.conf

Fixes #1599 
**Changes**
Reverts the nginx configuration file [which the docker compose setup expects.](https://github.com/open-zaak/open-zaak/blob/main/docker-compose.yml#L96)

[#1599] revert docker configuration file from `68ff9e1`

---

src/openzaak/components/autorisaties/tests/admin/test_autorisaties_admin.py
src/openzaak/components/autorisaties/utils.py

:sparkles:[#1584] fix autorisaties 500 error when related object deleted

---

CONTRIBUTING.md
GOVERNANCE.md
README.en.md
docs/introduction/open-source/index.rst

As [stated in email](https://lists.publiccode.net/hyperkitty/hyperkitty/list/openzaak-discuss@lists.publiccode.net/thread/A62NGGSGOTNEXAWXPK3B3X6J27DOB3A7/), the Foundation for Public Code will be winding down the office in Europe and will no longer be able to steward the OpenZaak codebase to the level which we aspire.
See also:
* https://blog.publiccode.net/news/2024/02/28/changes-at-the-europe-office.html
Fixes #1582
**Changes**
Removes text regarding active stewardship by the Foundation for Public Code.

Discontinue Foundation for Public Code stewardship

---

src/openzaak/components/catalogi/tests/admin/test_zaaktype_admin.py
src/openzaak/forms/fields.py

:sparkles:[#1577] Fix RelativeDeltaField allowing empty required values

---

src/openzaak/components/autorisaties/forms.py
src/openzaak/components/autorisaties/tests/admin/test_autorisaties_admin.py

Fixes #1594
**Changes**
* Validate for missing scopes in authorization admin form

 🐛 [#1594] Catch missing scopes error in authorization form

---

src/openzaak/components/autorisaties/forms.py
src/openzaak/components/autorisaties/tests/admin/test_autorisaties_admin.py
src/openzaak/components/autorisaties/utils.py
src/openzaak/tests/test_rewrite_host.py
src/openzaak/utils/middleware.py

Fixes #1585
**Changes**
* Only apply rewrite host middleware to API requests
* Specifically apply host rewrite for authorization admin notifications

 🐛 [#1585] Only rewrite host for API requests

---

docs/client-development/authentication.rst
src/openzaak/components/autorisaties/openapi.yaml
src/openzaak/components/besluiten/openapi.yaml
src/openzaak/components/catalogi/openapi.yaml
src/openzaak/components/documenten/openapi.yaml
src/openzaak/components/zaken/openapi.yaml
src/openzaak/utils/apidoc.py

Fixes #1626
Added some links to JWT stuff.
Added examples for Python, PHP. Java and JavaScript

:memo:[#1626] Add JWT examples to docs

---

docker-compose.yml

DB image in `docker-compose.yml` was out-of-date and didn't work with django app image anymore.

:whale: change DB image in docker-compose

---

src/openzaak/components/catalogi/admin/zaaktypen.py
src/openzaak/components/catalogi/tests/admin/test_zaaktype_admin.py

:children_crossing: [#1193] add ZaakTypeInformatieobjectType url in Zaaktype list admin page

---

src/openzaak/accounts/tests/test_2fa.py
src/openzaak/accounts/views.py
src/openzaak/urls.py

Fixes https://github.com/maykinmedia/open-api-framework/issues/40 partly
**Changes**
* Always use requests.hostname for 2FA app title

:wrench: Always use requests.hostname for 2FA app title

---

src/openzaak/components/catalogi/tests/factories/zaaktype.py
src/openzaak/management/commands/generate_data.py
src/openzaak/tests/management/test_generate_data.py

:sparkles: [#1748] add zaaktype.identificatie into generate_data command

---

openapitools.json

the generate-sdks job was failing (https://github.com/open-zaak/open-zaak/actions/runs/10937202249/job/30363822296?pr=1725) due to some network calls that were performed when validating the OAS, this is avoided by specifying the version of the generator-cli in openapitools.json
see also: https://github.com/OpenAPITools/openapi-generator-cli/issues/802

:green_heart: Fix failing CI due to openapitools issue

---

src/openzaak/components/zaken/admin/zaken.py
src/openzaak/components/zaken/tests/admin/test_zaak_admin.py

Fixes #1776 
**Changes**
Allows searching for zaken with local zaaktypes on `zaaktype_omschrijving` and `identificatie`.

[#1776] allow searching zaken on zaaktype omschrijving/identificatie

---

src/openzaak/components/zaken/api/filters.py
src/openzaak/components/zaken/tests/test_zaakinformatieobjecten.py

Fixes #1830
**Changes**
* Fix ZIO.informatieobject filter with external doc with the same host

🐛 [#1830] Fix ZIO.informatieobject filter with external doc with the same host

---

.bumpversion.cfg
CHANGELOG.rst
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/notificaties.md
src/openzaak/__init__.py
src/openzaak/components/catalogi/admin/admin_views.py
src/openzaak/components/catalogi/admin/side_effects.py
src/openzaak/components/urls.py
src/openzaak/components/views.py
src/openzaak/components/zaken/api/kanalen.py
src/openzaak/components/zaken/api/viewsets.py
src/openzaak/components/zaken/openapi.yaml
src/openzaak/components/zaken/tests/test_notifications_send.py
src/openzaak/components/zaken/tests/test_notifications_send_cmis.py
src/openzaak/notifications/tests/test_notification_retry.py
src/openzaak/notifications/tests/test_register_kanaal.py
src/openzaak/templates/index.html

Fixes https://github.com/open-zaak/open-notificaties/issues/156
Related PR in Open Notificaties:
- https://github.com/open-zaak/open-notificaties/pull/208
**Changes**
* Add (experimental) notificaties kenmerk for Zaak.zaaktype.catalogus
* Refer to self hosted notification documentation (instead of the reference implementation github)

:sparkles: [open-zaak/open-notificaties#156] Define kenmerk for Zaak.zaaktype.catalogus

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

I also added types to the issues that are currently open

:wrench: Use new issue types in templates instead of labels

---

src/openzaak/components/autorisaties/openapi.yaml
src/openzaak/components/besluiten/openapi.yaml
src/openzaak/components/catalogi/openapi.yaml
src/openzaak/components/documenten/openapi.yaml
src/openzaak/components/zaken/api/urls.py
src/openzaak/components/zaken/api/viewsets.py
src/openzaak/components/zaken/openapi.yaml
src/openzaak/components/zaken/tests/test_auth.py
src/openzaak/components/zaken/tests/test_zaken.py

Closes #1901
**Changes**
* Remove unnecessary geo headers for reserveer zaaknummer endpoint
**Checklist**

:bug: [#1901] Remove unnecessary geo headers for reserveer zaaknummer endpoint

---

docs/conf.py

jwt.io returns 500 with curl and within the ci. The reason is that it expects an `Accept-Language` header.
**Changes**
- Add Accept-Language header to jwt.io requests within the docs.
**Checklist**
(feel free to close if it's unnecessary)

add linkcheck_request_headers for jwt.io

---

.github/workflows/ci.yml
.github/workflows/code_quality.yml
CHANGELOG.rst
deployment/kubernetes/README.md
docker-compose.yml
docker/postgres.entrypoint-initdb.d/0001-open-zaak.sql
docs/development/getting_started.rst
docs/installation/prerequisites.rst
publiccode.yaml

Closes #1905
Tests are skipped for the last run, because there are no changes to .py files, here is a successful CI run: https://github.com/open-zaak/open-zaak/actions/runs/13438418210
**Changes**
* Upgrade postgres/postgis versions in CI
**Checklist**

:construction_worker: [#1905] Upgrade postgres/postgis versions in CI

---

src/openzaak/components/urls.py

it seems that the stable/1.0.x branch was removed from the VNG repo

:memo: Fix broken reference to autorisaties notificaties.md

---

CHANGELOG.rst
docs/api/experimental.rst
src/notificaties.md
src/openzaak/components/besluiten/api/kanalen.py
src/openzaak/components/besluiten/openapi.yaml
src/openzaak/components/besluiten/tests/test_notifications_send.py
src/openzaak/components/besluiten/tests/test_notifications_send_cmis.py
src/openzaak/components/documenten/api/kanalen.py
src/openzaak/components/documenten/openapi.yaml
src/openzaak/components/documenten/tests/test_notifications_send.py
src/openzaak/components/documenten/tests/test_notifications_send_cmis.py
src/openzaak/components/urls.py
src/openzaak/components/zaken/api/kanalen.py
src/openzaak/notifications/kanaal.py
src/openzaak/notifications/tests/test_register_kanaal.py

Closes open-zaak/open-notificaties#231
**Changes**
- Adds catalogus to kenmerken of `besluiten` & `documenten` kanaal.
- Moved the Kanaal class from `zaken/api/kanalen.py` to `utils` so that it could be used by the other components.
**Checklist**

[open-zaak/open-notificaties#231] Add catalogus kenmerk to besluiten & documenten kanaal

---

.github/workflows/ci.yml
Dockerfile
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/autorisaties/tests/admin/test_autorisaties_admin.py
src/openzaak/components/catalogi/tests/admin/test_admin_publish.py
src/openzaak/components/catalogi/tests/admin/test_besluittype_admin.py
src/openzaak/components/catalogi/tests/admin/test_informatieobjecttype_admin.py
src/openzaak/components/catalogi/tests/admin/test_notifications.py
src/openzaak/components/catalogi/tests/base.py
src/openzaak/components/catalogi/tests/test_catalogusautorisatie_sync.py
src/openzaak/components/documenten/tests/admin/test_eiocanonical_inline_audittrail.py
src/openzaak/components/documenten/tests/test_auth.py
src/openzaak/components/documenten/tests/test_objectinformatieobject.py
src/openzaak/components/documenten/tests/test_utils_cmis.py
src/openzaak/components/zaken/tests/test_validation_zaak.py
src/openzaak/components/zaken/tests/test_zaak_archive.py
src/openzaak/components/zaken/tests/test_zaakeigenschap.py
src/openzaak/components/zaken/tests/test_zaakinformatieobjecten_cmis.py
src/openzaak/conf/ci.py
src/openzaak/tests/management/test_generate_data.py
src/openzaak/tests/test_view_config.py

Closes #1712
Should cut CI time in half, resulting in ~10 mins: https://github.com/open-zaak/open-zaak/actions/runs/13859983660
**Changes**
* Upgrade coverage to 7.6.12
* Use faster password hasher when running tests
* Fix admin test that fired HTTP request to outside service
* Use uv to install deps in CI
* Install dependencies in docker build with UV
* Use setUpTestData instead of setUp to speed up testsuite
* Add missing mock for Catalogi API spec in archiving test
**Checklist**

 👷 [#1712] Further improvements to CI runtime

---

.github/workflows/ci.yml
docker-compose.factories.yml
performance_test/conftest.py
performance_test/create_data.py
performance_test/test_zaken_list.py
requirements/ci.txt
requirements/dev.txt
requirements/test-tools.in

Related issue: https://github.com/maykinmedia/open-api-framework/issues/114
I looked into codspeed, but I couldn't get it to work with their walltime instrument yet (https://github.com/maykinmedia/objects-api/pull/555), to at least get started with improving performance, I added similar tests to the ones I added in objects-api a few weeks back.
Not sure how consistent the results are in CI because we don't run it on dedicated runners, but it at least gives some indication of performance and can be used locally

✅ Add basic performance test for zaken list

---

src/openzaak/components/zaken/api/viewsets.py
src/openzaak/components/zaken/tests/test_auth.py

Closes https://github.com/open-zaak/open-zaak/issues/1960 
Increases performance by 25-30ms, so about 10-15% (from 214ms)
Baseline:
https://github.com/open-zaak/open-zaak/actions/runs/14055723188/job/39354660277#step:4:764
After removing catalogus select_related:
https://github.com/open-zaak/open-zaak/actions/runs/14108901120/job/39522128121#step:4:764
After replacing _zaaktype select_related with prefetch:
https://github.com/open-zaak/open-zaak/actions/runs/14130148304/job/39588155288#step:4:764
**Changes**
* Replace zaak._zaaktype select_related with prefetch
* Remove select_related on Zaak._zaaktype.catalogus for read operations
**Checklist**

:zap: [#1960] Optimize the Zaak list endpoint query

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Closes #1954 
Tried running performance tests with `_zaaktype` on the serializer instead of `zaaktype`, this bypasses django-loose-fk and just relies on drf HyperlinkedRelatedField to transform the fk into a URL
Baseline with 3500 zaken https://github.com/open-zaak/open-zaak/actions/runs/14055723188/job/39354660277
Only using local zaaktype (bypassing django-loose-fk): https://github.com/open-zaak/open-zaak/actions/runs/14058796484/job/39364290821?pr=1957
This seems to speed up the response time by about 35ms (had similar results locally). I think it is worth looking into optimizing django-loose-fk's serialization
Made a PR in django-loose-fk to improve serialization performance: https://github.com/maykinmedia/django-loose-fk/pull/40
Results seem to be about 25-35ms speedup for …

:zap: [#1954] Pin django-loose-fk to improve DRF field performance 

---

requirements/dev.in
requirements/dev.txt
src/openzaak/components/documenten/tests/test_enkelvoudiginformatieobject.py
src/openzaak/components/documenten/tests/test_enkelvoudiginformatieobject_cmis.py
src/openzaak/components/documenten/tests/test_verzending.py
src/openzaak/components/zaken/tests/test_create.py
src/openzaak/components/zaken/tests/test_zaak_expand.py
src/openzaak/conf/dev.py
src/openzaak/utils/expansion.py
src/openzaak/utils/middleware.py
src/openzaak/utils/mixins.py

this was causing overhead because it called reverse() for all objects returned by the query, even if expand was not supplied as a query parameter
Improves response time by up to 5-10% (if 100 objects are returned by a list endpoint)
- baseline https://github.com/open-zaak/open-zaak/actions/runs/14167931550/job/39685107057#step:4:765
- with changes https://github.com/open-zaak/open-zaak/actions/runs/14168658191/job/39687366304?pr=1961#step:4:762
Closes https://github.com/open-zaak/open-zaak/issues/1965
**Changes**
* Add middleware to profile request/response cycle with pyinstrument
* Don't run expand related code if expand query param is unused
* Add empty _expand attribute for detail operation if query param unused
**Checklist**
- …

:zap: [#1965] Don't run expand related code if expand query param is unused

---

src/openzaak/components/zaken/api/viewsets.py

a lot of duplicate queries were done due to this missing prefetch
**Checklist**

:zap: Add missing prefetch_related for Rol.statussen

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/openzaak/components/catalogi/api/serializers/besluittype.py
src/openzaak/components/catalogi/api/serializers/catalogus.py
src/openzaak/components/catalogi/api/serializers/eigenschap.py
src/openzaak/components/catalogi/api/serializers/relatieklassen.py
src/openzaak/components/catalogi/api/serializers/resultaattype.py
src/openzaak/components/catalogi/api/serializers/roltype.py
src/openzaak/components/catalogi/api/serializers/statustype.py
src/openzaak/components/catalogi/api/serializers/zaakobjecttype.py
src/openzaak/components/catalogi/api/serializers/zaaktype.py
src/openzaak/components/zaken/api/serializers/zaken.py
src/openzaak/components/zaken/tests/test_zaken.py
src/openzaak/utils/serializer_fields.py

Closes https://github.com/open-zaak/open-zaak/issues/1970
Improves median response time by about 10-20% in CI
Baseline on main: https://github.com/open-zaak/open-zaak/actions/runs/14265544211/job/39986422488#step:4:760
After changes: https://github.com/open-zaak/open-zaak/actions/runs/14268741960/job/39996806525?pr=1969#step:4:775
Related PR: https://github.com/maykinmedia/commonground-api-common/pull/82
**Changes**
* Use cached hyperlinked DRF fields for several serializers, to avoid redundant logic from being evaluated to determine the base URLs
**Checklist**

:zap: Optimize DRF hyperlinked fields

---

src/openzaak/components/besluiten/api/viewsets.py
src/openzaak/components/catalogi/api/viewsets/besluittype.py
src/openzaak/components/catalogi/api/viewsets/catalogus.py
src/openzaak/components/catalogi/api/viewsets/eigenschap.py
src/openzaak/components/catalogi/api/viewsets/informatieobjecttype.py
src/openzaak/components/catalogi/api/viewsets/relatieklassen.py
src/openzaak/components/catalogi/api/viewsets/resultaattype.py
src/openzaak/components/catalogi/api/viewsets/roltype.py
src/openzaak/components/catalogi/api/viewsets/statustype.py
src/openzaak/components/catalogi/api/viewsets/zaakobjecttype.py
src/openzaak/components/catalogi/api/viewsets/zaaktype.py
src/openzaak/components/documenten/api/viewsets.py
src/openzaak/components/zaken/api/viewsets.py
src/openzaak/utils/mixins.py

Both pagination and filtering cause `get_queryset` to be called additional times, while the result of this method does not change for the same request. By caching the result of get_queryset on the ViewSet instance we avoid constructing the same queryset multiple times and doing multiple extra database queries
This boosts performance for non-superusers especially, reduces median response time by about 10% in CI
Baseline on main: https://github.com/open-zaak/open-zaak/actions/runs/14312657378/job/40111275657#step:4:760
After changes: https://github.com/open-zaak/open-zaak/actions/runs/14327974895/job/40157184391?pr=1977#step:4:760
Closes #1976
**Changes**
* Cache the result of get_queryset per request
**Checklist**
- Experimental …

:zap: [#1976] Cache the result of get_queryset per request

---

src/openzaak/components/catalogi/api/viewsets/besluittype.py
src/openzaak/components/catalogi/api/viewsets/informatieobjecttype.py
src/openzaak/components/catalogi/api/viewsets/resultaattype.py
src/openzaak/components/catalogi/api/viewsets/statustype.py
src/openzaak/components/catalogi/api/viewsets/zaaktype.py
src/openzaak/components/zaken/api/viewsets.py

to speed up base performance of the following endpoints:
* /besluittypen
* /informatieobjecttypen
* /statustypen
* /resultaattypen
* /zaaktypen
* /statussen
* /zaakobjecten
**Changes**
* Add missing prefetch/select_related for several viewsets
**Checklist**

:zap: Add missing prefetch/select_related for several viewsets

---

src/openzaak/components/documenten/migrations/0009_auto_20220727_1517.py
src/openzaak/components/documenten/migrations/0027_auto_20230417_1415.py
src/openzaak/components/zaken/tests/test_migrations.py
src/openzaak/utils/migrations.py

This migration was part of bugfix release 1.9.1 and proved to fix the migration issue, so I want to forward port it to main to make sure this is also part of 1.20.0 and after
Closes #1940
**Changes**
* Fix data migrations for large number of objects
**Checklist**

:bug: [#1940] Fix data migrations for large number of objects

---

src/openzaak/components/zaken/api/viewsets.py
src/openzaak/components/zaken/models/zaken.py

and taking the first item from the prefetch result. This means we can avoid constructing a queryset for each Zaak in the result list, which reduces overhead
Baseline: https://github.com/open-zaak/open-zaak/actions/runs/14510665340/job/40708398457#step:4:756
After changes: https://github.com/open-zaak/open-zaak/actions/runs/14517707000/job/40730699309?pr=1998#step:5:63
Reduces mean/median response time for both regular and superusers by 5-10%
Closes #1999 
**Changes**
* Optimize current_status serialization by storing prefetch result on instance
**Checklist**

:zap: [#1999] Optimize current_status serialization by storing prefetch result on instance

---

.github/workflows/ci.yml

issue #2008 caused failures on master, a template for the admin changed and this was not tested because CI skipped tests
**Changes**
* Run tests in CI if templates changed
**Checklist**

:construction_worker: [#2008] Run tests in CI if templates changed

---

src/openzaak/components/documenten/query/django.py
src/openzaak/components/zaken/tests/test_auth.py
src/openzaak/utils/query.py

Closes #1937 partially
previously there were two separate filters: one to filter by all of the loose FK objects and another to specify the minimum required vertrouwelijkheidaanduiding per type. This has now been simplified by replacing the CASE clause and filtering on combinations of the loose FK objects and vertrouwelijkheidaanduiding. 
Example of the queries (slightly simplified)
Previous query:
```sql
WHERE ("zaken_zaak"."_zaaktype_id" IN (1,
2,
3,
4,
5,
6)
AND zaken_zaak.vertrouwelijkheidaanduiding <= (
CASE
WHEN "zaken_zaak"."_zaaktype_id" IN (1, 2, 3) 
THEN 1
WHEN "zaken_zaak"."_zaaktype_id" IN (4, 5, 6) 
THEN 2
```
New query:
```sql
WHERE 
(zaken_zaak._zaaktype_id IN (1,2,3) 
AND zaken_zaak.vertrouwelijkheidaanduiding <= 1)
OR
(zaken_zaak._zaaktype_id IN (4,5,6) 
AND …
```

:zap: [#1937] Remove redundant filter in authorizations filter query

---

src/openzaak/components/documenten/tests/models/test_last_version.py
src/openzaak/components/zaken/api/serializers/zaken.py
src/openzaak/components/zaken/openapi.yaml
src/openzaak/components/zaken/tests/test_zaken.py
src/openzaak/management/commands/generate_data.py
src/openzaak/tests/management/test_generate_data.py

Fixes #2011
this field was read only and was never populated, even if betalingsindicatie was set. Now it has been changed to show the label that corresponds with the betalingsindicatie value that the Zaak has
Baseline: https://github.com/open-zaak/open-zaak/actions/runs/14726552958/job/41330465681#step:5:62
After changes: https://github.com/open-zaak/open-zaak/actions/runs/14726565385/job/41330508336?pr=2001#step:5:62
**Changes**
* Show appropriate betalingsindicatieWeergave via serializer
**Checklist**

:bug: [#2011] Show appropriate betalingsindicatieWeergave via serializer

---

src/openzaak/tests/test_enabled_middleware.py
src/openzaak/utils/middleware.py

Closes #2025 
**Changes**
Added check in EnableMiddleware to to return None before InternalService db query if there is no component_type.
Added tests.
**Checklist**

:zap: [#2025] add component_type check for unnecessary db query's

---

docs/manual/archiving.rst

Closes #2002
**Changes**
- Adds a table to better explain the allowed afleidingswijze for each procestermijn
**Checklist**

:memo: [#2002] add procestermijn -> afleidingswijze table to documentation

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

this package includes optimizations for psycopg, improves performance:
before: https://github.com/open-zaak/open-zaak/actions/runs/15974414199#summary-45053011938
after: https://github.com/open-zaak/open-zaak/actions/runs/15992941551?pr=2087#summary-45109747269
**Changes**
* Add psycopg-binary to dependencies
**Checklist**

:heavy_plus_sign: Add psycopg-binary to dependencies

---

docker-compose.yml
docs/installation/config/env_config.rst
src/openzaak/conf/includes/base.py
src/openzaak/conf/production.py

**Changes**
* Fix incorrect default in docs for DB_CONN_MAX_AGE
**Checklist**

:memo: Fix incorrect default in docs for DB_CONN_MAX_AGE

---

src/openzaak/components/catalogi/tests/test_resultaattype.py
src/openzaak/components/catalogi/validators.py

Closes #2102
**Changes**
* make `BrondatumArchiefprocedureValidator` not crash when non-required attributes are missing
**Checklist**

fix creating resultaattype without non required archieve data 

---

docs/installation/config/env_config.rst
src/openzaak/conf/includes/base.py

to make sure Open Zaak can be used with pgbouncer
Related issue: https://github.com/maykinmedia/open-api-framework/issues/171
**Changes**
* Add envvar to disable server side cursors
**Checklist**

:wrench: Add envvar to disable server side cursors

---

src/openzaak/components/catalogi/api/filters.py
src/openzaak/components/catalogi/openapi.yaml

Closes #2105
**Changes**
changed description of `status` query param for ZaakType, InformatieObjectType and BesluitType in the Catalogi OAS
**Checklist**

:memo: [#2105] add how versions are defined for catalogi resources

---

src/openzaak/components/zaken/api/validators.py

Closes #2151 
**Changes**
Fixed spelling mistake and added missing space in the `deelzaken-not-closed` error message.
**Checklist**

chore: fixed spelling mistake and added missing space in `deelzaken-not-closed` error message

---

src/openzaak/management/commands/send_test_notification.py

Closes #...
**Changes**
When sending a test notification, I noticed that it was sent as `applicaton/x-www-form-urlencoded`, which does not match the NRC API specification. The [real implementation](https://github.com/maykinmedia/notifications-api-common/blob/cc982d6aa1159a4ea5ed9b7ae323816e11cd90cb/notifications_api_common/tasks.py#L29) in `notifications-api-common` does send it properly as json so this change aligns the test notification to be the same.
**Checklist**

Adhere to NRC specification when sending test notification

---

src/openzaak/components/besluiten/tests/test_audittrails_cmis.py
src/openzaak/components/besluiten/tests/test_besluit_with_external_zaak.py
src/openzaak/components/besluiten/tests/test_besluitinformatieobjecten.py
src/openzaak/components/documenten/tests/test_cmis_url_mapping.py
src/openzaak/components/documenten/tests/test_objectinformatieobject.py
src/openzaak/components/documenten/tests/test_objectinformatieobject_cmis.py
src/openzaak/components/zaken/tests/test_audittrails_cmis.py
src/openzaak/components/zaken/tests/test_zaak_archive.py
src/openzaak/components/zaken/tests/test_zaak_closed_cmis.py
src/openzaak/components/zaken/tests/test_zaak_delete.py
src/openzaak/components/zaken/tests/test_zaakcontactmoment.py
src/openzaak/components/zaken/tests/test_zaakinformatieobjecten.py
src/openzaak/components/zaken/tests/test_zaakverzoek.py

Closes maykinmedia/open-api-framework#172
**Changes**
**Checklist**

:recycle:  [maykinmedia/open-api-framework#172] clean up unneeded mock_service_oas_get calls
